### PR TITLE
Incremental use case update

### PR DESCRIPTION
**Pull request by jadie1**
This PR addresses issue #1790 and #1745.

It adds options to determine the order via random sorting, closest to median sorting, and closest to distribution sorting. 
It also adds options to specify the initial model size and incremental batch size.
The documentation has been updated appropriately. 

To test run:
```
python RunUseCase.py incremental_supershapes
```

### CODE REVIEW

**Comment by jadie1** [comment]
The use case test is failing because I added interaction to the use case. It requires input for the sorting method, initial model size, and batch size. I did this instead of adding parameters to RunUseCase.py because these options are super specific to this use case and all of the other RunUseCase.py tags are general.

@akenmorris and @nawazishkhan1-nk Do you think it would be better to add these three tags to RunUseCase.py or hard code them in the incremental_supershapes.py and add comments and documentation that clarify that these can be changed?

**Comment by akenmorris** [comment]
I would suggest that we use the "--interactive" flag that we've used in the past.  When it's specified, the script can ask for user input, otherwise it should use some defaults.

**Comment by jadie1** [comment]
This should be set to merge :) @akenmorris @nawazishkhan1-nk

**Review by akenmorris — APPROVED** [review]
Looks great.

**Pull request merged**
