### PR TITLE
Remove itkeigen

### PR DESCRIPTION
**Pull request by medakk**
I was seeing cases where one Eigen class was pulled in from our downloaded Eigen, and another one from ITK Eigen in one section of code. This PR gets rid of ITK Eigen. 

(This is not for the 6.0 release)

### CODE REVIEW

**Comment by cchriste** [comment]
I'm so excited for this to be fixed, and Linux seems like the place to try since it only takes 9 min to test. Go Pengins!

**Comment by medakk** [comment]
How do I do a no-cache rebuild(for everything: deps, conda, ccache, whatever else is involved)? The Studio windows build keeps trying to pull in something from itkeigen, and I want to rule out Github actions cache issues

```
AnalysisTool.obj : error LNK2019: unresolved external symbol "public: class itkeigen::Matrix<float,-1,1,0,-1,1> __cdecl shapeworks::Shape::get_point_features(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?get_point_features@Shape@shapeworks@@QEAA?AV?$Matrix@M$0?0$00$0A@$0?0$00@itkeigen@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: class QSharedPointer<class shapeworks::Shape> __cdecl shapeworks::AnalysisTool::get_mean_shape(void)" (?get_mean_shape@AnalysisTool@shapeworks@@QEAA?AV?$QSharedPointer@VShape@shapeworks@@@@XZ) [D:\a\ShapeWorks\build\Studio\src\Application\ShapeWorksStudio.vcxproj]
AnalysisTool.obj : error LNK2019: unresolved external symbol "public: void __cdecl shapeworks::Shape::set_point_features(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class itkeigen::Matrix<float,-1,1,0,-1,1>)" (?set_point_features@Shape@shapeworks@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Matrix@M$0?0$00$0A@$0?0$00@itkeigen@@@Z) referenced in function "public: class QSharedPointer<class shapeworks::Shape> __cdecl shapeworks::AnalysisTool::get_mean_shape(void)" (?get_mean_shape@AnalysisTool@shapeworks@@QEAA?AV?$QSharedPointer@VShape@shapeworks@@@@XZ) [D:\a\ShapeWorks\build\Studio\src\Application\ShapeWorksStudio.vcxproj]
Shape.obj : error LNK2019: unresolved external symbol "public: void __cdecl shapeworks::StudioMesh::interpolate_scalars_to_mesh(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class vnl_vector<double>,class Eigen::Matrix<float,-1,1,0,-1,1>)" (?interpolate_scalars_to_mesh@StudioMesh@shapeworks@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vnl_vector@N@@V?$Matrix@M$0?0$00$0A@$0?0$00@Eigen@@@Z) referenced in function "public: void __cdecl shapeworks::Shape::set_point_features(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class Eigen::Matrix<float,-1,1,0,-1,1>)" (?set_point_features@Shape@shapeworks@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Matrix@M$0?0$00$0A@$0?0$00@Eigen@@@Z) [D:\a\ShapeWorks\build\Studio\src\Application\ShapeWorksStudio.vcxproj]
D:\a\ShapeWorks\build\bin\RelWithDebInfo\ShapeWorksStudio.exe : fatal error LNK1120: 3 unresolved externals [D:\a\ShapeWorks\build\Studio\src\Application\ShapeWorksStudio.vcxproj]
Error: Process completed with exit code 1.
```

**Comment by akenmorris** [comment]
Rename the cache vars in the yml files so they won’t match anything.

**Comment by medakk** [comment]
This is weird:

* If "Build dependencies" are cached, Linux and Windows fail
* If I do a "fresh build" without the cache, Linux and Windows succeed.

Any idea what's happening here?

This is the error, when build dependencies are picked up from the cache:

```
 CMake Error at /home/runner/install/lib/cmake/ITK-5.0/Modules/ITKEigen3.cmake:15 (find_package):
  Could not find a package configuration file provided by "Eigen3" (requested
  version 3.3) with any of the following names:
-- Configuring incomplete, errors occurred!

See also "/home/runner/work/ShapeWorks/ShapeWorks/build/CMakeFiles/CMakeOutput.log".
    Eigen3Config.cmake
See also "/home/runner/work/ShapeWorks/ShapeWorks/build/CMakeFiles/CMakeError.log".
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/runner/install/lib/cmake/ITK-5.0/ITKModuleAPI.cmake:76 (include)
  /home/runner/install/lib/cmake/ITK-5.0/ITKModuleAPI.cmake:31 (itk_module_load)
  /home/runner/install/lib/cmake/ITK-5.0/ITKModuleAPI.cmake:129 (_itk_module_config_recurse)
  /home/runner/install/lib/cmake/ITK-5.0/ITKConfig.cmake:82 (itk_module_config)
  CMakeLists.txt:133 (FIND_PACKAGE)
```

**Comment by akenmorris** [comment]
So if you change the build dependencies then it works, but the next time it will fail?

**Comment by medakk** [comment]
> So if you change the build dependencies then it works, but the next time it will fail?

Yes. See the last two commits and the github actions results

(Mac is somehow exempt from this)

**Comment by medakk** [comment]
Okay, I see why:

```
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      with:
        path: ~/install
        key: ${{ runner.os }}-${{ hashFiles('**/build_dependencies.sh') }}
```

But the Eigen being used is in the build folder,  `set(Eigen3_DIR "/home/runner/build/eigen/build")` in `cat $HOME/install/lib/cmake/ITK-5.0/Modules/ITKEigen3.cmake`. I'm not sure why its using the Eigen from the build folder and not the install folder.

This happens on my local machine too(even before the remove_itkeigen changes). Can you check(possible by Ctrl+Clicking an Eigen include in your IDE, on any recent branch) whether its using the build Eigen or the install Eigen?

**Comment by medakk** [comment]
I believe this is working now! Please go ahead and review the changes

**Review by akenmorris — APPROVED** [review]
Looks good!

**Review by cchriste — APPROVED** [review]
yay!

**Pull request merged**
