### PR TITLE
Updated graphical abstract for 6.2 Release

### PR DESCRIPTION
**Pull request by sheryjoe**

### CODE REVIEW

**Comment by archanasri** [comment]
@sheryjoe Should we include the new C++ API documentation and the transform Python API to the graphical abstract?

**Review by akenmorris — APPROVED** [review]

**Comment by sheryjoe** [comment]
> @sheryjoe Should we include the new C++ API documentation and the transform Python API to the graphical abstract?

@archanasri I baked the c++ doc into the "Improved APIs and Use case documentation". Do you have suggestions for the transform API?

**Comment by archanasri** [comment]
> > @sheryjoe Should we include the new C++ API documentation and the transform Python API to the graphical abstract?
> 
> @archanasri I baked the c++ doc into the "Improved APIs and Use case documentation". Do you have suggestions for the transform API?

@sheryjoe Maybe we can quote it as "Transform API" with a picture of a matrix and an image/mesh?

**Comment by cchriste** [comment]
> > > @sheryjoe Should we include the new C++ API documentation and the transform Python API to the graphical abstract?
> > 
> > 
> > @archanasri I baked the c++ doc into the "Improved APIs and Use case documentation". Do you have suggestions for the transform API?
> 
> @sheryjoe Maybe we can quote it as "Transform API" with a picture of a matrix and an image/mesh?

If it helps, the specific improvements for transforms include:
- clearly separate creation of center of mass, rigid registration, and thin plate spline transforms
- fixed Python bindings for Mesh.createTransform and Mesh.applyTransform
- pass all affine transforms between Python and C++ and transparent, modifiable numpy matrices

**Comment by sheryjoe** [comment]
> > > > @sheryjoe Should we include the new C++ API documentation and the transform Python API to the graphical abstract?
> > > 
> > > 
> > > @archanasri I baked the c++ doc into the "Improved APIs and Use case documentation". Do you have suggestions for the transform API?
> > 
> > 
> > @sheryjoe Maybe we can quote it as "Transform API" with a picture of a matrix and an image/mesh?
> 
> If it helps, the specific improvements for transforms include:
> 
> * clearly separate creation of center of mass, rigid registration, and thin plate spline transforms
> * fixed Python bindings for Mesh.createTransform and Mesh.applyTransform
> * pass all affine transforms between Python and C++ and transparent, modifiable numpy matrices

@cchriste thanks. @archanasri  please update release notes accordingly. I will update the abstract.

**Comment by sheryjoe** [comment]
updated the abstract.

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
