### PR TITLE
Updated docs and release 6 notes

### PR DESCRIPTION
**Pull request by sheryjoe**

### CODE REVIEW

**Comment by akenmorris** [comment]
FYI, a new branch will need to be made and have the desired commits cherry picked since this branch contains commits from master not intended for the release.

**Comment by sheryjoe** [comment]
@archanasri could you help out with what @akenmorris just suggested?

**Comment by archanasri** [comment]
Yeah I'll create another branch

**Comment by akenmorris** [comment]
Is this ready to go?  I'm happy to do what I suggested, but I wanted to wait until this is ready.

**Comment by archanasri** [comment]
Closing this PR since #1146 is merged.

**Pull request closed without merging**
