### PR TITLE
New mesh from distance transforms

### PR DESCRIPTION
**Pull request by jadie1**
Riddhish helped me make NewMeshFromDT which works but it does not do smoothing or mesh decimation like MeshFromDistanceTransforms was supposed to. If this is added it could replace  MeshFromDistanceTransforms.

### CODE REVIEW

**Comment by akenmorris** [comment]
The test are failing due to a missing vtk python module:

Traceback (most recent call last):
3:   File "ellipsoidMain.py", line 14, in <module>
3:     from RunEllipsoid import *
3:   File "/Users/runner/runners/2.164.0/work/ShapeWorks/ShapeWorks/Examples/Python/RunEllipsoid.py", line 28, in <module>
3:     from GroomUtils import *
3:   File "/Users/runner/runners/2.164.0/work/ShapeWorks/ShapeWorks/Examples/Python/GroomUtils.py", line 11, in <module>
3:     import vtk
3: ModuleNotFoundError: No module named 'vtk'

I started adding a build of VTK with python in another branch, and while it builds, it's not ready yet because it requires the user to set several items to PYTHONPATH and LD_LIBRARY_PATH.  Unless we can resolve those, we need to add vtk to conda_install.sh

**Comment by jadie1** [comment]
Thanks Alan,

I think I accidentally made the MeshFromDT branch off of my FemurUseCase
branch, I meant to make it off of master and just add the one file and
update the make. Should I remove it and make another?

Jadie

**Comment by 0leks** [comment]
Yeah you should probably cancel this pull and merge off of master and cherrypick your commit. It doesn't make sense to merge the in-progress FemurUseCase branch right now

**Comment by jadie1** [comment]
I will close this and make a new pull request without the FemurUseCase changes.

**Pull request closed without merging**
