### PR TITLE
Fix ellipsoid evaluation

### PR DESCRIPTION
**Pull request by medakk**
Fixes paths, but group differences not working in Studio yet

### CODE REVIEW

**Comment by sheryjoe** [comment]
> but group differences not working in Studio yet

why is that?

**Comment by sheryjoe** [comment]
@medakk could you also update doc/new/ssm-eval.md ?

**Comment by medakk** [comment]
I'm not sure. @akenmorris says it used to work at some point. I recall now that this is why I used View2 here instead of Studio.

**Comment by akenmorris** [comment]
> why is that?

See #777

**Pull request merged**
