### PR TITLE
Studio Landmark Support

### PR DESCRIPTION
**Pull request by akenmorris**
This PR adds full support for landmarks in Studio:

image

* The data module is redesigned with collapsible panels similar to the analysis module
* Panels for the data table, landmarks, constraints, and notes are provided
* Landmark definitions are added to the Project class and spreadsheet. Each definition has:
  * Name
  * Color
  * Comment
  * Associated domain
* Added toolbar button to show/hide landmarks 
* Landmarks can be added with ctrl+click, and grabbed and moved along a surface (#1640)
* Landmarks can be used in new support for landmark registration (#922)
* Landmarks can be used as initial points in Optimization (#1423)

### CODE REVIEW

**Comment by akenmorris** [comment]
Initial 3D picking of landmarks is not working on windows.  They are placed in the correct X/Y location but the depth is incorrect.  Looking at the VTK picking code there must be something wrong with OpenGL depth buffer settings.  Some potentially relevant discussion:

https://discourse.vtk.org/t/problem-in-vtk-8-2-with-defaultformat-and-qvtkopenglwidget-on-windows-10-intel/998

https://gitlab.kitware.com/vtk/vtk/-/issues/17844

**Comment by akenmorris** [comment]
Fixed problems on Windows.  Checked Linux and it works for me there.

**Comment by jadie1** [comment]
@akenmorris could you send us an example project spreadsheet for testing?

**Comment by akenmorris** [comment]
Do you want one with landmarks already defined?

[landmarks.zip](https://github.com/SCIInstitute/ShapeWorks/files/7945285/landmarks.zip)

It should be super simple to open studio, drag some shapes (femurs, left atriums, whatever), add landmarks and use them.

**Comment by jadie1** [comment]
Okay thanks!

**Review by jadie1 — APPROVED** [review]
Looks like everything is working now!

**Pull request merged**
