### PR TITLE
Address #615 by creating a script to run ShapeWorksStudio from bin

### PR DESCRIPTION
**Pull request by akenmorris**
This addresses #615.

More complicated than I would have liked, but a symlink doesn't work and you can't directly write an executable file using CMake, so it has to write elsewhere and copy.

### CODE REVIEW

**Comment by cchriste** [comment]
I don't know how to verify this works because `make install` doesn't work for me. 
Here are the errors when I run make install:
```
ERROR: no file at "/usr/local/opt/libiodbc/lib/libiodbc.2.dylib"
ERROR: no file at "/Applications/Postgres.app/Contents/Versions/9.6/lib/libpq.5.dylib"
```

**Comment by cchriste** [comment]
The latest pre-release build from four days ago doesn't seem to have the script, so I can't try that either.

**Comment by cchriste** [comment]
> The latest pre-release build from four days ago doesn't seem to have the script, so I can't try that either.

I also tried the [action from this pull request](https://github.com/SCIInstitute/ShapeWorks/actions/runs/562275972), which has no such script.

**Comment by akenmorris** [comment]
> I also tried the action from this pull request, which has no such script.

Yep, it just wasn't making it into the installer.  Should be fixed now (I see it in the deployment PR file)

**Comment by cchriste** [comment]
Finally able to download the GitHub artifact and ShapeWorksStudio.exe works!

**Review by cchriste — APPROVED** [review]

**Comment by cchriste** [comment]
And the Nullsoft installer: sweet! 
So both the start menu item and the command line version run. Not sure how the start menu version activates the conda environment, and didn't go deep trying to do anything, but it started up fine.

**Comment by akenmorris** [comment]
> So both the start menu item and the command line version run. Not sure how the start menu version activates the conda environment, and didn't go deep trying to do anything, but it started up fine.

What start menu version?  For Python?

**Comment by cchriste** [comment]
For Studio. That’s the only one I saw after installation.

**Comment by akenmorris** [comment]
Oh, I see.  None of our executables (including studio) require conda to be installed in order to run.  Users only need to install and activate conda to run the python stuff.  This is the same for your local builds on your machine, you don't need to activate your conda environment to run the `shapeworks` executable or `ShapeWorksStudio`.

**Pull request merged**
