### PR TITLE
Automatic deployment of master branch changes

### PR DESCRIPTION
**Pull request by akenmorris**
This PR adds automatic deployment of changes to master to latest-mac, latest-windows, and latest-linux GH releases.  The release is overwritten each time.

### CODE REVIEW

**Comment by akenmorris** [comment]
You can rename, sure.  But GH releases AFAIK have to be tied to a tag.  This automatic deployment relies on re-using the "latest-<platform>" tag.  I suppose if you wanted to store a specific one, you could create a new tag, download the assets, and upload them to the other release.

**Comment by akenmorris** [comment]
@sheryjoe 

They are located here:

https://github.com/SCIInstitute/ShapeWorks/releases/tag/latest-windows
https://github.com/SCIInstitute/ShapeWorks/releases/tag/latest-mac
https://github.com/SCIInstitute/ShapeWorks/releases/tag/latest-linux

With some more work, we can eventually combine these into a single GH release.

They are tagged with the git-hash for reference.

We are not storing any more than the latest at the moment.

**Comment by sheryjoe** [comment]
@akenmorris Please update the readme to include links to the dev builds. Thanks.

**Comment by akenmorris** [comment]
Should be ready to go now.

**Pull request merged**
