### PR TITLE
Notebook Visualization Fix

### PR DESCRIPTION
**Pull request by riddhishb**
This commit basically removes the interactive flag which was a misleading nomenclature and replaced it with a notebook flag in the pyvista plotters.

[A] When the notebook flag is False (this is the default now), it generates a render window and the visualization is performed in this window, you can close this window (tested on Linux) without affecting the rest of the code.

[B] When the notebook flag is True the rendering process is still done via OpenGL which requires an empty window that will pop open, but the visualization itself will be inline in the notebook:
This causes two problems and the suggestion is to never use this.
- Either you cannot close the window or if you close it then the notebook hangs
- Due to communication between the renderer and notebook the interactivity is very laggy

I have changed the backend plot functions and notebooks accordingly, and by default, it uses option [A].

Testing needed for Windows and Mac -- I suggest running [this notebook](https://github.com/SCIInstitute/ShapeWorks/blob/master/Examples/Python/notebooks/tutorials/getting-started-with-exploring-segmentations.ipynb)

Fixes issue #1314 and other lagging problems.

### CODE REVIEW

**Review by jadie1 — APPROVED** [review]
I tested all the notebooks on Linux and it seems to work well. Having the output in the notebook was a little more intuitive but I think this is a better user experience. 

If someone tests on windows can you see if this resolves issue #1113

**Comment by cchriste** [comment]
> If someone tests on windows can you see if this resolves issue #1113

booting it up now...

**Comment by cchriste** [comment]
> If someone tests on windows can you see if this resolves issue #1113

It does not.

**Comment by cchriste** [comment]
It works fine, but the notebooks now have missing images. Maybe this is just a coincidence and they were already missing. 
These should be [re-]added.

133708565-ac58fb17-ffaa-4ee1-8ac3-10e444ac257a_LI

**Comment by cchriste** [comment]
> I tested all the notebooks on Linux and it seems to work well. Having the output in the notebook was a little more intuitive but I think this is a better user experience.

The part I find frustrating is that multiple outputs cannot be simultaneously displayed. Once upon a time I thought this was possible...

**Review by cchriste — CHANGES_REQUESTED** [review]
Add missing images.

**Comment by riddhishb** [comment]
Yeah, that annoyed me too, but unfortunately, I cannot add these images, as they are not actually images it's interactive blocks either it's detached from a notebook or in there. and unfortunately, those square boxes can be removed as far as I know

**Comment by cchriste** [comment]
> Yeah, that annoyed me too, but unfortunately, I cannot add these images, as they are not actually images it's interactive blocks either it's detached from a notebook or in there. and unfortunately, those square boxes can be removed as far as I know

Clicking on the cell shows its contents. Looks like an image missing from the sci.utah.edu/~shapeworks directory. So what needs to be done is for the screenshots to be [re-created and] re-uploaded to this location. Anyone know where that is?
In the meantime, a scan through the notebooks to identify and recapture the missing material will help find what needs to be re-uploaded and even say what it should be named. (Please don't simply delete these lines. I know cuz' I was tempted to do the same :). 

image

**Comment by riddhishb** [comment]
> > Yeah, that annoyed me too, but unfortunately, I cannot add these images, as they are not actually images it's interactive blocks either it's detached from a notebook or in there. and unfortunately, those square boxes can be removed as far as I know
> 
> Clicking on the cell shows its contents. Looks like an image missing from the sci.utah.edu/~shapeworks directory. So what needs to be done is for the screenshots to be [re-created and] re-uploaded to this location. Anyone know where that is?
> In the meantime, a scan through the notebooks to identify and recapture the missing material will help find what needs to be re-uploaded and even say what it should be named. (Please don't simply delete these lines. I know cuz' I was tempted to do the same :).
> 
> image

alright let me fix this.

**Comment by cchriste** [comment]
Is it possible the links from the SCI server are only accessible from a restricted set of URLs? I'm looking at PR #1472 and there are links there that are not accessible from my localhost (ex: https://sci.utah.edu/~shapeworks/doc-resources/gifs/ellipsoid_mode1.gif). Because it's a big update, I'm not sure where/if that link was simply not there before, or where to look on the SCI server to find these. 

Can someone (@sheryjoe @jadie1 @archanasri @iyerkrithika21 @akenmorris) please tell us where to find the SCI resources directory? Here are images showing the missing resources in the other PR I mentioned:
Screen Shot 2021-09-20 at 1 56 26 PM

Screen Shot 2021-09-20 at 1 46 48 PM
Screen Shot 2021-09-20 at 1 48 47 PM

**Comment by riddhishb** [comment]
Yeah I am facing the same issue navigating to a site with the resource gives me permission error.
https://sci.utah.edu/~shapeworks/doc-resources/pngs/shape_boundary.png

**Comment by riddhishb** [comment]
I checked all the notebooks, @cchriste I think this can be merged now.

**Pull request merged**
