### PR TITLE
Update Datasets docs with new folder structure

### PR DESCRIPTION
**Pull request by 0leks**
Added info on the normalized folder names.

Better view of the new md file here: [https://github.com/SCIInstitute/ShapeWorks/blob/update_use_case_doc/Documentation/Datasets.md](https://github.com/SCIInstitute/ShapeWorks/blob/update_use_case_doc/Documentation/Datasets.md)

### CODE REVIEW

**Comment by sheryjoe** [comment]
@0leks 
"Left Atrium dataset License" -> doesn't open the license file.
Here is what is opened when clicking on "License"
{
    "message": "Read access denied for folder 5e55fa758886bab730d72c43 (user None).",
    "type": "access"
}


"Ask Oleks to add you to the list of developers. (oleks@sci.utah.edu)" Is there a way we could make this less centralized? 

"Use DatasetUtils.uploadNewDataset(datasetName, datasetPath) to upload."
What if we have a zip file?

"Example file structure:"
Can you add a description of what each subfolder should contain? expected extensions? and comment on file names convention?
@akenmorris do we need to add the spreadsheet here for file matching?

**Comment by 0leks** [comment]
@sheryjoe 
I fixed the license link, I assume it got messed up when some files were changed on the data portal.

> "Ask Oleks to add you to the list of developers. (oleks@sci.utah.edu)" Is there a way we could make this less centralized?

Adding to the developer list is an inherently centralized process. I can give someone else instructions on how to do this.

> "Use DatasetUtils.uploadNewDataset(datasetName, datasetPath) to upload."
> What if we have a zip file?

If you have a zip file you also have the unzipped version that you were using for ShapeWorks

> "Example file structure:"
Can you add a description of what each subfolder should contain? expected extensions? 

I added some details on the contents and expected extensions. I was unsure of what to write for some of them and would appreciate some info on this.

> and comment on file names convention?

What do you mean by the file names convention? Is this referring to the naming of actual data files such as: `seg.ellipsoid_00.nrrd`?

**Comment by akenmorris** [comment]
> @akenmorris do we need to add the spreadsheet here for file matching?

When it's ready, yes.

**Comment by 0leks** [comment]
there are a lot of supported image file types. I think it would be too cluttered to include them all in this documentation. Is it okay to just include this link: https://insightsoftwareconsortium.github.io/itk-js/docs/image_formats.htmlBioRad
BMP
DICOM
DICOM Series
ITK HDF5
JPEG
GE4,GE5,GEAdw
Gipl (Guys Image Processing Lab)
LSM
MetaImage
MINC 2.0
MGH
MRC
NifTi
NRRD
Portable Network Graphics (PNG)

**Comment by sheryjoe** [comment]
Yes, including a link is reasonable.

**Comment by akenmorris** [comment]
Ok to merge, @sheryjoe ?

**Comment by sheryjoe** [comment]
As of now, it looks good. This should be updated once we have the spreadsheet for the datasets in place.

**Pull request merged**
