### PR TITLE
Deploy gh pages

### PR DESCRIPTION
**Pull request by akenmorris**
This PR adds a github action workflow that will deploy the mkdocs on gh-pages for pushes to master branch.

### CODE REVIEW

**Comment by sheryjoe** [comment]
@akenmorris how could i test this PR? should I run the deploy mkdocs script in Support?

**Comment by akenmorris** [comment]
I don't think that script will work for you.  It's using the $GITHUB_TOKEN that's given by the GitHub Action.

I tested it by changing the branch to deploy_gh_pages and seeing that it updated the gh-pages.

https://github.com/SCIInstitute/ShapeWorks/runs/1261317769?check_suite_focus=true

**Comment by sheryjoe** [comment]
We should also include  the python autodoc for shapeworks commands before mkdocs deploy.

**Comment by akenmorris** [comment]
Yes, that's a good point.

**Comment by akenmorris** [comment]
Ugh, well, I guess this needs to go in with the build actions since we need 'shapeworks' executable built in order to generate this documentation.  Shall we just put it on one platform?  Linux?

**Comment by sheryjoe** [comment]
> Ugh, well, I guess this needs to go in with the build actions since we need 'shapeworks' executable built in order to generate this documentation. Shall we just put it on one platform? Linux?

Yeah, we can deploy on linux.

**Comment by akenmorris** [comment]
I've moved it there and the checks are now running.

**Comment by akenmorris** [comment]
I think this is ready to merge.

**Pull request merged**
