### PR TITLE
Pin package versions 

### PR DESCRIPTION
**Pull request by iyerkrithika21**
Added versions for the following packages based on the Windows installation and my Linux build : 

- [x] statsmodel
- [x] trimesh
- [x] shapely
- [x] nbstripout
- [x] ipyvtklink
- [x] ipyvtk_simple
- [x] itkwidgets
- [x] ipywidgets

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
@akenmorris  this partially resolved #1580

**Comment by akenmorris** [comment]
Awesome. Should we try all the same ITK 5.2.0post1?

**Comment by iyerkrithika21** [comment]
> 
> 
> Awesome. Should we try all the same ITK 5.2.0post1?
I am not sure how to change/include this in install_shapeworks.bat/sh.
Are you talking about changing the version of ITK in build_dependencies?

**Comment by akenmorris** [comment]
No, this is the itk installed by pip:

  if ! pip install itk==5.0.1;                          then return 1; fi

**Pull request merged**
