### PR TITLE
After Studio runs in the examples, output lines for the user to execu…

### LINKED ISSUE #512: Instructions for opening analyze file without running the full pipeline
From Amy Lenz:

Can you provide instructions on how to re-visualize the analyze.xml after the initial correspondence model has been executed?  For example, it may take a while to run the model, successful results are achieved

### PR DESCRIPTION
**Pull request by akenmorris**
…te to re-run studio.

Resolves #512

### CODE REVIEW

**Comment by akenmorris** [comment]
Example:


To re-run ShapeWorksStudio, run:

 cd /Users/amorris/sci/shapeworks/code/Examples/Python
 ShapeWorksStudio ./TestEllipsoids/PointFiles//analyze.xml


Shapeworks Pipeline Complete!

**Comment by sheryjoe** [comment]
Should this be added to the documentation?

**Comment by akenmorris** [comment]
Where?  For each of the use cases?

**Comment by sheryjoe** [comment]
May be. Or have top-level documentation on how to run a use case and run studio later.

**Comment by akenmorris** [comment]
How about this?

https://github.com/SCIInstitute/ShapeWorks/blob/studio_rerun/Documentation/UseCases.md

See the section about "Running subsequent analysis"

**Comment by sheryjoe** [comment]
Looks good!

**Pull request merged**
