### PR TITLE
Moving Documentation to MkDocs

### PR DESCRIPTION
**Pull request by sheryjoe**
This PR improves our documentation via:

- Adopting mkdocs for improved documentation accessibility using unified navigation and deployment
- Cleaned up markdown files (including grammar and spell check)
- Better organization and naming conventions 
- Separating docs for users vs developers
- Added a unified structure of use case documentation for existing ones with instructions for developers on how to add a new use case
- Added some background for users about shape modeling with links to segmentation softwares to turn their images to shapes
- Added documentation for developers to contribute to ShapeWorks documentation

**Documentation is far from being complete and comprehensive, but this is the first step towards having all of us as a team contribute to documentation within a unified infrastructure.** Please, visit docs/todo (or https://sciinstitute.github.io/ShapeWorks/todo) for the internal list of documentation todos, which will be converted to Github issues. Please, feel free to contribute and check-done for some of these todos.

**Deployed documentation:** https://sciinstitute.github.io/ShapeWorks/
**Source documentation:** mkdocs.yml and docs/

### CODE REVIEW

**Comment by cchriste** [comment]
I veto GitHub urls for local documentation files. If mkdocs is doing this we should find a way to fix it, but I suspect it's just incorrect understand of markdown. The party starts at the top-level README.md:
```
Quick Links
=====================
- [How to install ShapeWorks?](http://sciinstitute.github.io/ShapeWorks/users/install)
```
should be...
```
Quick Links
=====================
- [How to install ShapeWorks?](docs/users/install.md)
```

Using grip (as described in docs/dev/markdown.md and already installed by conda_installs.md), the cool indexed organization of mkdocs doesn't show unless you run the mkdocs serve command described in docs/dev/mkdocs.md, but that's okay for simply editing individual files. Or we can consolidate are documentation to always tell people to use mkdocs, but in that case we should install it using conda_installs.sh.

**Comment by sheryjoe** [comment]
```
> Quick Links
> =====================
> - [How to install ShapeWorks?](docs/users/install.md)
> ```

If we directly link to source md files, we will lose the navigable organization that mkdocs provides. These quick links are for users, so wouldn't it be more useful for them to be linked to the built documentation where they can navigate to other items on the documentation?

> Using grip (as described in docs/dev/markdown.md and already installed by conda_installs.md), the cool indexed organization of mkdocs doesn't show unless you run the mkdocs serve command described in docs/dev/mkdocs.md, but that's okay for simply editing individual files. Or we can consolidate are documentation to always tell people to use mkdocs, but in that case we should install it using conda_installs.sh.

mkdocs and other related libs for documentation are already included in conda installs. We can update docs/dev/markdown.md to recommend mkdocs serve (and point to mkdocs.md) and highlight the downside of grip.

**Comment by cchriste** [comment]
> If we directly link to source md files, we will lose the navigable organization that mkdocs provides. These quick links are for users, so wouldn't it be more useful for them to be linked to the built documentation where they can navigate to other items on the documentation?

Relative paths work fine in GitHub. That's what we've had all along*. When GitHub pretties up the markdown files it also changes the relative paths to point to specific locations in the current source tree. By forcing such paths to master we lose the ability to have different documentation (or anything else at all, such as use case descriptions, etc) in different branches.

* for example, look at the Ellipsoid Use Case link on this page: https://github.com/SCIInstitute/ShapeWorks/blob/master/Documentation/GettingStarted.md
`This <a href="/SCIInstitute/ShapeWorks/blob/master/Documentation/UseCases/Ellipsoid.md">example</a>...`  
And look at the link the raw source:
`This [example](UseCases/Ellipsoid.md)...`

> mkdocs and other related libs for documentation are already included in conda installs. We can update docs/dev/markdown.md to recommend mkdocs serve (and point to mkdocs.md) and highlight the downside of grip.

I've just been following the instructions in docs/dev/mkdocs.md. It tells you to install mkdocs using pip, create a new docs using `mkdocs new .` (which needed a space between new and .), and go from there. After that didn't work I found the mkdocs.yml in the root directory, but `mkdocs serve` from there didn't work either. Since you just told me conda_installs now installs mkdocs I'm doing that now... and... it works just like grip, automatically updating as individual files are changed. Grip is a little closer to the file and is therefore worth keeping. But we need local paths. It makes `mkdocs serve` usable for local development and makes it possible to have independent documentation trees for each branch.

As for the directories themselves, for which there are several links in the docs, for instance in docs/use-cases/use-cases.md, there must be some way for mkdocs to provide relative paths rather than hardcoding them.

**Comment by medakk** [comment]
mkdocs should [transform it into the right links](https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links):

image

**Comment by sheryjoe** [comment]
All paths in docs and mkdocs are relative paths to md files (not static generated ones). The only exception (which needed to resolved) is paths to python scripts (e.g., RunUseCase.py .. etc) on master. Mkdocs converts those relative paths to the corresponding links and we don't have to worry about this.

**Comment by cchriste** [comment]
> All paths in docs and mkdocs are relative paths to md files (not static generated ones). The only exception (which needed to resolved) is paths to python scripts (e.g., RunUseCase.py .. etc) on master (see the internal todo). Mkdocs converts those relative paths to the corresponding links and we don't have to worry about this.

Please look at README.md. It's filled with explicit web paths that need to be changed to be relative.
We also need to figure out how to tell mkdocs to create GitHub links to directories and python scripts.

**Comment by sheryjoe** [comment]
> > If we directly link to source md files, we will lose the navigable organization that mkdocs provides. These quick links are for users, so wouldn't it be more useful for them to be linked to the built documentation where they can navigate to other items on the documentation?
> 
> Relative paths work fine in GitHub. That's what we've had all along*. When GitHub pretties up the markdown files it also changes the relative paths to point to specific locations in the current source tree. By forcing such paths to master we lose the ability to have different documentation (or anything else at all, such as use case descriptions, etc) in different branches.
> 
> * for example, look at the Ellipsoid Use Case link on this page: https://github.com/SCIInstitute/ShapeWorks/blob/master/Documentation/GettingStarted.md
>   `This <a href="/SCIInstitute/ShapeWorks/blob/master/Documentation/UseCases/Ellipsoid.md">example</a>...`
>   And look at the link the raw source:
>   `This [example](UseCases/Ellipsoid.md)...`
> 
> > mkdocs and other related libs for documentation are already included in conda installs. We can update docs/dev/markdown.md to recommend mkdocs serve (and point to mkdocs.md) and highlight the downside of grip.
> 
> I've just been following the instructions in docs/dev/mkdocs.md. It tells you to install mkdocs using pip

The first statement in the mkdocs.md
:fa-info-circle: Important: The below installations are added to conda_insalls scripts.

> create a new docs using `mkdocs new .` (which needed a space between new and .), and go from there. 

This is when setting up the project, i.e. creating the mkdocs.yml This is not needed as we already set up our mkdocs.yml 

Nice catch about the space!

**Comment by sheryjoe** [comment]
> > All paths in docs and mkdocs are relative paths to md files (not static generated ones). The only exception (which needed to resolved) is paths to python scripts (e.g., RunUseCase.py .. etc) on master (see the internal todo). Mkdocs converts those relative paths to the corresponding links and we don't have to worry about this.
> 
> Please look at README.md. It's filled with explicit web paths that need to be changed to be relative.
> We also need to figure out how to tell mkdocs to create GitHub links to directories and python scripts.

Back to my point, these paths are meant to take the user to the generated documentation (htmls) not to the md files. That is why are they are web paths. The main readme is not included in the mkdocs (it is not compiled to a static html) unless we move it to docs and this way we will lose the main readme page for the repo.

**Comment by cchriste** [comment]
> > All paths in docs and mkdocs are relative paths to md files (not static generated ones). The only exception (which needed to resolved) is paths to python scripts (e.g., RunUseCase.py .. etc) on master (see the internal todo). Mkdocs converts those relative paths to the corresponding links and we don't have to worry about this.
> 
> Please look at README.md. It's filled with explicit web paths that need to be changed to be relative.
> We also need to figure out how to tell mkdocs to create GitHub links to directories and python scripts.

Another couple things:
- MarkDown has a handy standard of automatically showing a README.md if the browser gets pointed at a directory with one in it. Grip does this, so setting a relative path in docs/dev/new-use-case.py to ../../Examples/Python automatically brings up its README.md. We should consider adding README.md files to all the docs directories rather than docs/name/name.md like we're doing now. At the very least this makes development using grip simpler.
- It's handy that GitHub knows how to show a source file in a pretty, formatted way. This is why I wonder if there is some way to make mkdocs point to that file in the source tree to which the documentation belongs. Because we don't want to have only a single documentation for every branch to reference. It ruins our ability to develop documentation.

**Comment by cchriste** [comment]
> > > All paths in docs and mkdocs are relative paths to md files (not static generated ones). The only exception (which needed to resolved) is paths to python scripts (e.g., RunUseCase.py .. etc) on master (see the internal todo). Mkdocs converts those relative paths to the corresponding links and we don't have to worry about this.
> > 
> > 
> > Please look at README.md. It's filled with explicit web paths that need to be changed to be relative.
> > We also need to figure out how to tell mkdocs to create GitHub links to directories and python scripts.
> 
> Back to my point, these paths are meant to take the user to the generated documentation (htmls) not to the md files. That is why are they are web paths. The main readme is not included in the mkdocs (it is not compiled to a static html) unless we move it to docs and this way we will lose the main readme page for the repo.

Try clicking on one and you'll see they don't do that. All they do is prevent anyone from seeing updated documentation in another branch.

**Comment by sheryjoe** [comment]
> > > > All paths in docs and mkdocs are relative paths to md files (not static generated ones). The only exception (which needed to resolved) is paths to python scripts (e.g., RunUseCase.py .. etc) on master (see the internal todo). Mkdocs converts those relative paths to the corresponding links and we don't have to worry about this.
> > > 
> > > 
> > > Please look at README.md. It's filled with explicit web paths that need to be changed to be relative.
> > > We also need to figure out how to tell mkdocs to create GitHub links to directories and python scripts.
> > 
> > 
> > Back to my point, these paths are meant to take the user to the generated documentation (htmls) not to the md files. That is why are they are web paths. The main readme is not included in the mkdocs (it is not compiled to a static html) unless we move it to docs and this way we will lose the main readme page for the repo.
> 
> Try clicking on one and you'll see they don't do that. All they do is prevent anyone from seeing updated documentation in another branch.

They don't do what? I tried those links on my end and they took me to the generated documentation. To see modified docs on another branch, you could check out this branch and do mkdocs serve. The users only see the built documentation (gh-pages branch) regardless of which branch it was built from.

**Comment by sheryjoe** [comment]
@cchriste Can you point me to examples of these hard-coded links that (1) are not in the main readme and (2) not links to *.py files?

**Comment by cchriste** [comment]
Links to directories and/or .py files (or any other language) that are
hard-coded **are the problem.**

I also don’t like the links in README.md but that’s a more arguable issue.

**Comment by sheryjoe** [comment]
> Links to directories and/or .py files (or any other language) that are hard-coded **are the problem.** I also don’t like the links in README.md but that’s a more arguable issue.

I know. Please point me to examples in docs as I mentioned in my last comment.

**Comment by cchriste** [comment]
Another solution could be to make a rule to prohibit such links in our
documentation and instead copy the relevant portions of these files to the
.md (note: this also means you can have nice formatting suggetions, like...
well, I don’t know how to quote here, but the
triple-tick-followed-by-language-name syntax does this).

The links to directories can be similarly replaced with something lasting
and independent of what is currently committed to the master branch of the
shapeworks github repository.

Next question: is this documentation included with a downloadable build? I
know these builds include our python examples as well, and users may want
to modify/explore those. It’s not unreasonable for our non-programmer users
to even create new python use cases (would they still call them “use cases”
when they’re just trying to use shapeworks?).

**Comment by sheryjoe** [comment]
@cchriste I can't really see your point unless you point to specific examples. As mentioned in the todo list, links to the py files are still to be fixed. Otherwise, all links are relevant paths in the docs folder.

**Comment by cchriste** [comment]
> @cchriste I can't really see your point unless you point to specific examples. As mentioned in the todo list, links to the py files are still to be fixed. Otherwise, all links are relevant paths in the docs folder.

```
(shapeworks) cam@ananda:~/code/ShapeWorks/ShapeWorks/docs$ find . -type f -name "*" -exec grep "SCIInstitute/ShapeWorks/tree/master" {} \; -print
* **New, flexible ShapeWorks project file format:** New spreadsheet (XLSX) based project file format that can easily handle multiple shape modeling scenarios. It is now fully integrated into Studio. See the [ellipsoid studio example](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Studio/ellipsoid.xlsx) for an example.
./about/release-notes.md
- [ ] How can we use repo_url in markdown files to link to repo files? Currently, we use hard code it whenever we link to a page: https://github.com/SCIInstitute/ShapeWorks/tree/master
./todo.md
The use case is located at: [Examples/Python/ellipsoid_fd.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/ellipsoid_fd.py)
To run the use case, run [RunUseCase.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/RunUseCase.py) with proper tags. The tags control the type of input data and the optimization method. See [Getting Started with Use Cases](../use-cases/use-cases.md#running-use-case) for the full list of tags.
This calls [ellipsoid_fd.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/ellipsoid_fd.py) to perform the following.
* Optimizes particle distribution (i.e., the shape/correspondence model) on the new shape samples by calling optimization functions in [OptimizeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/OptimizeUtils.py). See [Optimizing Shape Model](#optimizing-shape-model) for details about algorithmic parameters for optimizing the shape model.
* Launches ShapeWorksStudio to visualize the use case results (i.e., optimized shape model on the new shapes and the pre-trained shape model) by calling functions in [AnalyzeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/AnalyzeUtils.py)
In [ellipsoid_fd.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/ellipsoid_fd.py), the following is defined.
./use-cases/fixed-domain-ellipsoid.md
The use case is located at: [Examples/Python/left_atrium.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/left_atrium.py)
To run the use case, run [RunUseCase.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/RunUseCase.py) with proper tags. The tags control the type of input data and the optimization method. See [Getting Started with Use Cases](../use-cases/use-cases.md#running-use-case) for the full list of tags.
This calls [left_atrium.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/left_atrium.py) to perform the following.
* Grooms the images and segmentations by calling data preprocessing functions in [GroomUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/GroomUtils.py). See [Grooming Data](#grooming-data) for details about these preprocessing steps.
* Optimizes particle distribution (i.e., the shape/correspondence model) by calling optimization functions in [OptimizeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/OptimizeUtils.py). See [Optimizing Shape Model](#optimizing-shape-model) for details about algorithmic parameters for optimizing the shape model.
* Launches ShapeWorksStudio to visualize the use case results (i.e., optimized shape model and the groomed data) by calling functions in [AnalyzeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/AnalyzeUtils.py)
./use-cases/left-atrium.md
The use case is located at: [Examples/Python/femur.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/femur.py)
To run the use case, run [RunUseCase.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/RunUseCase.py) with proper tags. The tags control the type of input data and the optimization method. See [Getting Started with Use Cases](../use-cases/use-cases.md#running-use-case) for the full list of tags.
This calls [femur.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/femur.py) to perform the following.
* Grooms the images and meshes by calling data preprocessing functions in [GroomUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/GroomUtils.py). See [Grooming Data](#grooming-data) for details about these preprocessing steps.
* Optimizes particle distribution (i.e., the shape/correspondence model) by calling optimization functions in [OptimizeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/OptimizeUtils.py). See [Optimizing Shape Model](#optimizing-shape-model) for details about algorithmic parameters for optimizing the shape model.
* Launches ShapeWorksStudio to visualize the use case results (i.e., the optimized shape model and the groomed data) by calling functions in [AnalyzeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/AnalyzeUtils.py)
./use-cases/femur.md
The [ellipsoid.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/ellipsoid.py) use case represents the standard use version of a shape modeling workflow using ShapeWorks. It includes the full pipeline for processed (i.e., prepped/groomed) as well as unprocessed data. 
The use case is located at: [Examples/Python/ellipsoid.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/ellipsoid.py)
To run the use case, run [RunUseCase.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/RunUseCase.py) with proper tags. The tags control the type of input data and the optimization method. See [Getting Started with Use Cases](../use-cases/use-cases.md#running-use-case) for the full list of tags.
This calls [ellipsoid.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/ellipsoid.py) to perform the following.
* Grooms the segmentations by calling data preprocessing functions in [GroomUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/GroomUtils.py). See [Grooming Data](#grooming-data) for details about these preprocessing steps.
* Optimizes particle distribution (i.e., the shape/correspondence model) by calling optimization functions in [OptimizeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/OptimizeUtils.py). See [Optimizing Shape Model](#optimizing-shape-model) for details about algorithmic parameters for optimizing the shape model.
* Launches ShapeWorksStudio to visualize the use case results (i.e., optimized shape model and the groomed data) by calling functions in [AnalyzeUtils.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/AnalyzeUtils.py)
./use-cases/ellipsoid.md
The use cases are located at: [Examples/Python](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python). When a use case is run, the dataset is automatically downloaded. 
./use-cases/use-cases.md
- Add `<use-case-name>.py` python script to [Examples/Python](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/), where the `<use-case-name>` is a descriptive name for the use case, typically associated with the class of shapes to be modeled (e.g., anatomy name)
- Update [Examples/Python/RunUseCase.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/RunUseCase.py) to add the new use case to the list of cases. Look for the line `parser.add_argument("--use_case" ...)`. Make sure to use the `<use-case-name>` to the use case list.
To add the documentation of the new dataset, add a markdown file `<use-case-name>.md` in [docs/use-cases](https://github.com/SCIInstitute/ShapeWorks/tree/master/docs/use-cases/) with the following structure. Please use the [Naming and Organization](../dev/mkdocs.md#naming-and-organization) conventions currently deployed for ShapeWorks documentation.
- **Running the Use Case**: Instructions to run the use case that highlights the specific use of [RunUseCase.py](https://github.com/SCIInstitute/ShapeWorks/tree/master/Examples/Python/RunUseCase.py) tags specifically for this use case. 
./dev/new-use-case.md
```

**Comment by cchriste** [comment]
Also, plese `git rm -r MovedToDocs`

**Comment by cchriste** [comment]
I resign on my argument against hard-coded links to sciinstitute.github.io/shapeworks since that's good for main readme. 

The question of what is included in downloadable builds stands. Users shouldn't have to go to GitHub.io or anywhere else online to read the manual

**Comment by sheryjoe** [comment]
All these examples are links to py files, which are to be fixed. --- that's my point :(

mkdocs.yml has a repo_url variable that I think we should be able to use it to avoid hardcoded links, but so far I haven't found any resources that document how to use mkdocs yml meta information within the md files.

**Comment by cchriste** [comment]
> All these examples are links to py files, which are to be fixed. --- that's my point :(

Perhaps my suggestion of producing these documentation files without links should be considered.

> mkdocs.yml has a repo_url variable that I think we should be able to use it to avoid hardcoded links, but so far I haven't found any resources that document how to use mkdocs yml meta information within the md files.

I looked for this, but even if it exists, the links to the GitHub URLs for a given commit (yes, even more specifically than a branch, but emphasizes the challenge) are non-obvious and the chicken-and-egg problem still exists: checking documentation changes still wouldn't be possible till after a push.

**Comment by sheryjoe** [comment]
> The question of what is included in downloadable builds stands. Users shouldn't have to go to GitHub.io or anywhere else online to read the manual

Agreed. We should package the "site" folder that mkdocs generates. So "mkdocs build" should be added to the github actions, @akenmorris?

**Comment by akenmorris** [comment]
Yeah, we are including the docs folder in the deployments.

**Comment by sheryjoe** [comment]
> > All these examples are links to py files, which are to be fixed. --- that's my point :(
> 
> Perhaps my suggestion of producing these documentation files without links should be considered.

I support this in general. We could remove these links and give directions in the documentation on where to find them (either in a repo or on a local/cloned version). This way, we will not provide any links within the documentation except for (1) web links (e.g. segmentation softwares, markdown edits ... etc) and (2) links to documentation pages within docs (using relative paths). 

The caveat to this disconnection is the users would have to do the extra steps for finding out where to find these files (e.g., femur.py).

**Comment by cchriste** [comment]
> Yeah, we are including the docs folder in the deployments.

Can we include the mkdocs version?

**Comment by sheryjoe** [comment]
> Yeah, we are including the docs folder in the deployments.

Docs is not the generated documentation. I am refering to the "site" folder that mkdocs generate when you do mkdocs serve or build or gh-deploy. Basically the content of the gh-pages branch.

**Comment by cchriste** [comment]
> > Perhaps my suggestion of producing these documentation files without links should be considered.
> 
> I support this in general. We could remove these links and give directions in the documentation on where to find them (either in a repo or on a local/cloned version). This way, we will not provide any links within the documentation except for (1) web links (e.g. segmentation softwares, markdown edits ... etc) and (2) links to documentation pages within docs (using relative paths).
> 
> The caveat to this disconnection is the users would have to do the extra steps for finding out where to find these files (e.g., femur.py).

Ultimately the users need to find these locations on their local system, so one might consider this an advantage.

**Comment by akenmorris** [comment]
Yeah, we should include any generated documentation as well.  Well, I wouldn't include doxygen.

**Comment by sheryjoe** [comment]
> > > Perhaps my suggestion of producing these documentation files without links should be considered.
> > 
> > 
> > I support this in general. We could remove these links and give directions in the documentation on where to find them (either in a repo or on a local/cloned version). This way, we will not provide any links within the documentation except for (1) web links (e.g. segmentation softwares, markdown edits ... etc) and (2) links to documentation pages within docs (using relative paths).
> > The caveat to this disconnection is the users would have to do the extra steps for finding out where to find these files (e.g., femur.py).
> 
> Ultimately the users need to find these locations on their local system, so one might consider this an advantage.

Yeah. You are right. I will remove these links then and add the instructions.

**Comment by akenmorris** [comment]
FYI, we are already including autogenerated docs.  For example:

# Run auto-documentation
PATH=$INSTALL_DIR/bin:$PATH
python -c "import DocumentationUtils;DocumentationUtils.generateShapeWorksComma\
ndDocumentation('Documentation/ShapeWorksCommands/ShapeWorksCommands.md')"
cp -a Documentation "package/${VERSION}"

**Comment by sheryjoe** [comment]
> > Yeah, we are including the docs folder in the deployments.
> 
> Can we include the mkdocs version?

Good point. In conda installs, we install the latest version. But pinning the mkdocs version (maybe adding mkdocs --version could to github actions?) that built the docs would avoid potential future incompatibilities. @akenmorris

**Comment by sheryjoe** [comment]
> FYI, we are already including autogenerated docs. For example:
> 
> ```
> # Run auto-documentation
> PATH=$INSTALL_DIR/bin:$PATH
> python -c "import DocumentationUtils;DocumentationUtils.generateShapeWorksCommandDocumentation('Documentation/ShapeWorksCommands/ShapeWorksCommands.md')"
> cp -a Documentation "package/${VERSION}"
> ```

- The path to the md file should be changed to docs/tools/ShapeWorksCommands.md
- Then, mkdocs build or gh-deploy should then be triggered
- cp command should then copy the "site" folder or content of gh-pages branch to the Documentation folder of the package.

**Comment by sheryjoe** [comment]
I will add another exception for links in docs:
https://github.com/SCIInstitute/ShapeWorks/releases

**Comment by akenmorris** [comment]
Just add whatever is necessary to Support/package.sh and Support/package_window.sh

**Comment by sheryjoe** [comment]
All links outside docs are removed (replaced with location) except for weblinks, shapeworks releases, and data portal.

**Comment by sheryjoe** [comment]
> Just add whatever is necessary to Support/package.sh and Support/package_window.sh

@akenmorris Please review my changes to the support files.

**Comment by sheryjoe** [comment]
@akenmorris @cchriste is this ready to merge? 

@akenmorris did you review my changes to the packaging scripts?

**Comment by cchriste** [comment]
I like the changes that were made in order to avoid hardcoded paths outside
if the current tree, so it looks good to me.

**Comment by akenmorris** [comment]
@sheryjoe , the changes look fine, but last I saw a build via GitHub Action, the windows build failed.  I've fixed that problem (I think).  The PR does not run the action due to a conflict in Commands.cpp.

**Review by cchriste — APPROVED** [review]

**Comment by sheryjoe** [comment]
Should we merge then? @akenmorris

**Pull request merged**
