### PR TITLE
Evaluatessm

### PR DESCRIPTION
**Pull request by medakk**
This adds functionality to evaluate SSMs.

* Introduces 4 new commands to the shapeworks executable:
    * readparticlesystem
    * compactness
    * generalization
    * specificity

* Tests for these commands have been added, along with the required dataset(<125KB).

* The OptionParser has been modified to support multiple file arguments, like `1.particle 2.particle --` or `*.particles --`

* Some duplicated code and particle IO specific code has been moved to Libs/Particles

* Adds eigen as a dependency via conda

### CODE REVIEW

**Comment by medakk** [comment]
This PR makes conda a requirement to build shapeworks. In the github workflow, build commands are now prefixed with `conda activate shapeworks && `

**Comment by akenmorris** [comment]
Nice work.

**Comment by medakk** [comment]
Sorry, I'd missed a typo. Added another commit (f42943f)

**Comment by akenmorris** [comment]
If I just run "shapeworks readparticlesystem" I get a segfault:

$  shapeworks readparticlesystem
zsh: segmentation fault  shapeworks readparticlesystem

**Comment by akenmorris** [comment]
Our help says:

Usage: readparticlesystem [args]...

reads a particle system

Options:
  -h, --help            show this help message and exit
  --names=MULTISTRING   name of file to read

But I can't use an equals sign with --names:

shapeworks readparticlesystem --names=*_world.particles -- compactness
zsh: no matches found: --names=*_world.particles

I must use a space:

shapeworks readparticlesystem --names *_world.particles -- compactness
1

**Comment by medakk** [comment]
I made a special case for the multistring when printing the help message in b43fe09
I'm not sure if its the best way to do this, but I can't think of anything else. The optparse library wasn't designed for multiple arguments.

**Pull request merged**
