### PR TITLE
Cache particle -> triangle index

### PR DESCRIPTION
**Pull request by medakk**
This PR modifies many APIs to pass around particle index along with position. This is only useful for the mesh domain right now: to store a cache of particle index -> triangle index. This prevents many expensive KDtree lookups, resulting in a speedup(1:35 hours to 0:50 hours in femur_mesh use case)

### CODE REVIEW

**Review by HeavenlyBerserker — COMMENTED** [review]
I don't see any issues. Anything, in particular, you want me to test?

**Comment by medakk** [comment]
@HeavenlyBerserker not in particular. Maybe just give it a once-over and run it on a use case to make sure everything works right.

**Comment by HeavenlyBerserker** [comment]
Runs on the ellipsoid use_case

**Comment by medakk** [comment]
I'm seeing differing results on the crushed can dataset in this branch vs master. Might be because of #812. Investigating.

**Comment by medakk** [comment]
Works now, was a bug with barycentric coords

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
