### PR TITLE
Grooming Segmentation path fix

### PR DESCRIPTION
**Pull request by iyerkrithika21**

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
Please don't merge yet.

**Comment by akenmorris** [comment]
FYI, we will need to cherry pick commits for these fixes as this PR branch contains commits from master not intended for the release.

**Comment by iyerkrithika21** [comment]
What should be the base branch? release_v6.0 or release_v6.0c ?

**Comment by akenmorris** [comment]
release_v6.0c,  I've removed release_v6.0 as I accidentally merged commits from master into it.

**Pull request closed without merging**
