### PR TITLE
little things that tidy up the 6.1 release 

### PR DESCRIPTION
**Pull request by cchriste**
Included items that have _no effect on functionality_:
- remove --use_case from RunUseCase command instructions in platform readmes

### CODE REVIEW

**Comment by akenmorris** [comment]
I think it was fine to make --use-case optional, but it's now an error to specify it? (#1349).

Is there any way to make the old command work too?

**Comment by cchriste** [comment]
> Is there any way to make the old command work too?

I don't think it should be optional. It's always required.

**Comment by akenmorris** [comment]
I get that it's required.  It's just a backward compatibility thing.

For example, when I do ctrl-r from my terminal to search for "--groom_images" or whatever to bring up a RunUseCase command, all those commands will fail now.  Or if I had a script that was running RunUseCase.py, I have to modify it now for 6.1.  And I also won't be able to swap between 6.0 and 6.1.

I think it's probably pretty minor for RunUseCase.py, but I just bring it up in general that if it's ever simple to maintain previous syntax, we should opt for it.

**Comment by sheryjoe** [comment]
I agree with @akenmorris

**Comment by cchriste** [comment]
> I think it's probably pretty minor for RunUseCase.py, but I just bring it up in general that if it's ever simple to maintain previous syntax, we should opt for it.

I agree with you about maintaining previous syntax _to some reasonable degree_. 

But in this case I think it's neither simple (parameters without double-dash are required; calling this script without that parameter is impossible), nor a big deal like you said. Plus it makes things _much_ clearer to the user since `--help` no longer shows this parameter under `optional arguments:` as it did before.

**Comment by akenmorris** [comment]
Is this PR ready to merge?

**Pull request merged**
