### PR TITLE
Open meshes

### PR DESCRIPTION
**Pull request by 0leks**
Lots of changes. The update to new TriMesh changed a bunch of files so I recommend skipping past all of those when reviewing.

- Added optimization visualizer (only works for mesh domains currently)
- Particle splits move particle and new particle in opposite directions by half the update.
- Removed energy decay stopping criterion that was never encountered
- Removed meanTime averaging that was causing adaptive time step to not be adaptive.
- minimum time step is initially 1 and after half way through iterations it decays to near 0.
- maximumUpdateAllowed now scales update vector down and continues update instead of reducing time step to satisfy.
- update that increases energy (bad move) now skips that particle update instead of trying over and over until time step is very low.

Need to test to make sure image domain use cases still work. Note that because of the changes to the optimization loop and particle splitting, the resulting models will be different but should be of similar quality.
- [x] ellipsoid
- [x] femur
- [ ] left atrium

### CODE REVIEW

**Comment by akenmorris** [comment]
Is there a dataset/test to try it on?

**Comment by sheryjoe** [comment]
@0leks could you add the sphere lumps and hemisphere datasets to include them in the unit tests?

**Comment by 0leks** [comment]
I added a lumps.py use_case and uploaded the lumps dataset to the data portal. For the hemisphere, What do you think is the best way to add hemisphere?

**Comment by sheryjoe** [comment]
This hemisphere could be used as data for unit testing the mesh optimization. @akenmorris ?

**Comment by 0leks** [comment]
[gifs, images, and point files comparing master branch vs open_mesh branch for femur](https://drive.google.com/drive/folders/1-sjnsUwfm1IzXNK9iIDgFhD_jLOD2a-h?usp=sharing)

**Comment by sheryjoe** [comment]
> gifs, images, and point files comparing master branch vs open_mesh branch for femur

These look good to me. How about ellipsoid and LA? Do we also plan to test optimizing on meshes for this PR?

**Comment by akenmorris** [comment]
@0leks , this branch has a lot of compilation errors, on all platforms.  Are some updated files perhaps not committed?

**Comment by 0leks** [comment]
For windows its a bunch of different test errors. I assumed it was also test errors for linux/mac so thats an oops.

**Comment by akenmorris** [comment]
Ok, I just saw that they all failed and since it wasn't compiling on Mac/Linux, I just assumed it wasn't on Windows either.  Take a look at my commit and see if that's all ok.

**Comment by 0leks** [comment]
Looks good, I'm waiting for deps to build before I can test anything, I messed up my stuff.

**Comment by cchriste** [comment]
The output suggests this isn't a functionality failure, but due to a missing file. Any thoughts? Should we dig in with a debugger?
```
3: [ RUN      ] OptimizeTests.use_normals_test
2178
3: Verbosity 0: This will be the only output on your screen, unless there are any errors. Increase the verbosity if needed.
2179
3: Sampled point outside the narrow band: [1, 3, 10]
2180
3: unknown file: Failure
2181
3: C++ exception with description "/home/runner/work/ShapeWorks/ShapeWorks/Libs/Optimize/ParticleSystem/itkParticleImageDomain.h:217:
2182
3: itk::ERROR: DataObject(0x34966e0): Attempt to sample at a point outside the narrow band: [1, 3, 10]. Consider increasing the narrow band" thrown in the test body.
2183
3: [  FAILED  ] OptimizeTests.use_normals_test (5816 ms)
```

**Comment by cchriste** [comment]
> The output suggests this isn't a functionality failure, but due to a missing file. Any thoughts? Should we dig in with a debugger?
> 
> 2179
> 3: Sampled point outside the narrow band: [1, 3, 10]

Okay, dug in deep with a debugger. The issue is a throw from (our local) itkParticleImageDomain.h:217. 
This is outside my understanding of this code. Who can help debug the problem?

**Comment by akenmorris** [comment]
@0leks , I some some changes that changed a radius of m_Spacing * 5.0 to just m_Spacing as a maximum radius.  What was the purpose of this?

**Comment by akenmorris** [comment]
@0leks , I found that I had to increase the narrow band to 30 for the simple sphere example to work.  Any idea why?

**Comment by akenmorris** [comment]
Ok, you shifted the x5.0 elsewhere. Maybe we shouldn’t call it spacing anymore.

**Comment by 0leks** [comment]
[added ellipsoid comparison gifs & point files](https://drive.google.com/drive/folders/1-sjnsUwfm1IzXNK9iIDgFhD_jLOD2a-h?usp=sharing)
Excellent results for both master branch and mesh branch for ellipsoid

**Comment by 0leks** [comment]
@akenmorris I agree on not calling it spacing any more. It is set as the spacing of the images but it is actually the particle split distance.

**Comment by 0leks** [comment]
Struggling a lot with getting decent left_atrium results on open_mesh branch after merging in shapeworks_improv with the bounding box fix.
I've tried the default regularization values and 20000 -> 10 but both models have a bunch of swapping particles.
[https://drive.google.com/drive/folders/1tf6xiRRMQaNZKxzuMIxbp0etA5qBUfJa?usp=sharing](https://drive.google.com/drive/folders/1tf6xiRRMQaNZKxzuMIxbp0etA5qBUfJa?usp=sharing)

**Comment by cchriste** [comment]
> Struggling a lot with getting decent left_atrium results on open_mesh branch after merging in shapeworks_improv with the bounding box fix.
> I've tried the default regularization values and 20000 -> 10 but both models have a bunch of swapping particles.
> https://drive.google.com/drive/folders/1tf6xiRRMQaNZKxzuMIxbp0etA5qBUfJa?usp=sharing

I'll fix the LA "fix" (shapeworks_improv) right now, but in fact the merge was of _executable_\_improv. Both have essentially the same issue in that they are not performing the glorified resize that was the result of the old ICP nearly-noop executable. The fix will do this so the results are just as they were before (a glorified resize). 

Can someone please give me a "tutorial" I can cut and paste to re-run this mesh test in order to check results?
Thanks.

**Comment by 0leks** [comment]
What do you mean by mesh test?

**Comment by cchriste** [comment]
> What do you mean by mesh test?

The results you shared in your message earlier were generated by some means. I was requesting instructions.

**Comment by 0leks** [comment]
I see, it is not a mesh test, it is the left_atrium image use case
From `Examples/Python`
Run `$ python RunUseCase.py --use_case left_atrium`

**Comment by cchriste** [comment]
> I see, it is not a mesh test, it is the left_atrium image use case
> From `Examples/Python`
> Run `$ python RunUseCase.py --use_case left_atrium`

Thank you for the clarification. Is there a way to quickly run it (i.e., `--tiny_test`) to see draft results illustrating the issue? Or do I have to wait a day every time I try (two days on my laptop)?

**Comment by 0leks** [comment]
The original issue with bounding boxes only manifested for the full run.
The model quality can only be judged for a full run.
So yes, you have to wait a day each run  :(

**Comment by cchriste** [comment]
Merged with fixed resampling in shapeworks_improv branch, started a run before bed, and this is where it stopped. Any help understanding would be appreciated. Thanks!
```
Done.
writing ./TestLeftAtrium/PointFiles//1024//transform ...Done.
Writing cutting plane points...
Writing ...Done.
Done.
Finished optimization!!!
------------------------------
*** Initialize Step
------------------------------

itk::ExceptionObject (0x7f90a2f939e0)
Location: "unknown" 
File: /Users/cam/code/ShapeWorks/ShapeWorks-alt/Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
Line: 161
Description: itk::ERROR: DataObject(0x7f915b126180): Distance transform queried for a Point, [2.80677e+07, 1.06563e+07, -4.68312e+06], outside the given image domain. Consider increasing the narrow band


General exception caught.
	Returncode: 1
	Output: None
```

**Comment by cchriste** [comment]
My linux system is up to day two or three of running this use case. The last bit of output indicating a change of tasks is this: 
```Writing ./TestLeftAtrium/PointFiles//1024//CARMA1404.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1421.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1432.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1460.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1462.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1467.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1500.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1504.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1522.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Done.
writing ./TestLeftAtrium/PointFiles//1024//transform ...Done.
Writing cutting plane points...
Writing ...Done.
Done.
Finished optimization!!!
------------------------------
*** Initialize Step
------------------------------
split number = 1

Particle count: 1024
1. 8689ms
Energy: 2133.9
2. 3806ms
Energy: 20129
3. 3796ms
Energy: 20638.9
4. 3798ms
Energy: 20739.7
5. 3790ms
Energy: 23836.5
6. 3795ms
Energy: 24096.9
7. 3793ms
Energy: 23530.6
8. 3792ms
```
...and it's up to 2972, finishing a new one every 30s or so. Can't finish on Windows (Anaconda shell) (details in #667) and can't run in git-bash on Windows (details in #664). And I need my OSX system to work, so haven't tried that one for a couple days.

**Comment by cchriste** [comment]
Day 4: Linux LA test case still not finished. Periodically writing "point files" and "point with attribute" files, as shown here:
```
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1504.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_world.particles and ./TestLeftAtrium/PointFiles//1024//CARMA1504.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_local.particles files...with 1024points...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA1522.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_world.particles and ./TestLeftAtrium/PointFiles//1024//CARMA1522.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_local.particles files...with 1024points...Done.
Done.
writing ./TestLeftAtrium/PointFiles//1024//transform ...Done.
Writing point with attributes files...
Writing ./TestLeftAtrium/PointFiles//1024//CARMA0046.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
Writing ./TestLeftAtrium/PointFiles//1024//CARMA0072.laendo_no_veins.isores.center.pad.com.aligned.cropped.tpSmoothDT_wptsFeatures.particles...with 6 attributes per point...Done.
```

**Comment by akenmorris** [comment]
Screen Shot 2020-08-25 at 3 53 14 PM

The blue dot is the original particle.  Green is the new point that is ok, and red is the bad point.  The initial update vectors from the split are 2.5mm.

array([-2.31052 , -0.105768, -0.948854])
>>> np.linalg.norm(x)
2.500002690706552

After the domain ApplyConstraints call, the new position is 4.46mm from the original point.  This will indeed exceed the 4mm narrow band.

I will have to add some more debugging statements and do more runs.  I don't see why the domain ApplyConstraints would do anything but push the particle back to the surface.

One potential problem with the new splitting code is that it applies a ProjectVectorToSurfaceTangent on the random direction, but this is for the first particle.  The second particle is then given the negative of this direction, but do we need to reproject this?  On second thought, maybe it will be the same.

**Comment by sheryjoe** [comment]
ApplyConstraints is doing a root trapping (newton raphson) to project the particle back to the surface (zero level set of the distance transform). Does the image domain has two zero level sets? Is this due to the narrow band that it projects the particle to the outer surface of the narrow band?

**Comment by cchriste** [comment]
Not sure how much farther this made it, seems to be exactly as far as the earlier errors noted in this PR six days ago (on OSX):
```
Done.
writing ./TestLeftAtrium/PointFiles//1024//transform ...Done.
Writing cutting plane points...
Writing ...Done.
Done.
Finished optimization!!!
------------------------------
*** Initialize Step
------------------------------
Sampled point outside the narrow band: [24.6508, -8.61641, 32.4667]

itk::ExceptionObject (0x2bb54e0)
Location: "unknown"
File: /scratch/cam/code/ShapeWorks/Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
Line: 217
Description: itk::ERROR: DataObject(0x1df0ed0): Attempt to sample at a point outside the narrow band: [24.6508, -8.61641, 32.4667]. Consider increasing the narrow band


General exception caught.
        Returncode: 1
        Output: None
```
Do these errors have anything to do with the previous two messages about (mis)placement of points?

**Comment by akenmorris** [comment]
I believe the problem is due to some changes that were made regarding the spacing and neighborhood size settings.  There was a constant shifted that is increasing the size of the particle split distance.  In most cases it is still covered by the 4mm narrow but, but in this corner case it did not.

This brought up a slight unrelated issue with the gradient narrow band image, see #671.

I will test a fix for this.

**Comment by akenmorris** [comment]
With the latest commit, the LA use case now completes and appears to have as good or better model.  I'm a little confused about what the existing shape model is.  The latest download from master has a zip with shape models that only go up to 512 particles, but the python example uses 1024.  So I compared to a recent full run from after the optimize multiscale.

Before:

shapeworks read-particle-system --names *_world.particles -- generalization compactness specificity
Particle system generalization: 3.40004
Particle system compactness: 0.447922
Particle system specificity: nan

After:

Particle system generalization: 3.30982
Particle system compactness: 0.453202
Particle system specificity: 2.2142

Additionally, the explained variance graph is pretty similar and shows 45.3% explained with the first mode compared to 44.8%  before.

Since I fixed the particle split distance, it may affect the other runs, in particular the mesh examples.

**Comment by sheryjoe** [comment]
Great! Thanks Alan! Any other tests/cases to run before merging this?

**Comment by akenmorris** [comment]
I think it's worth re-running the mesh cases.  I think they should works just fine though.

**Comment by akenmorris** [comment]
Femur mesh now:

image

**Comment by sheryjoe** [comment]
This looks similar to what Oleks reported.

**Comment by akenmorris** [comment]
> This looks similar to what Oleks reported.

Does anyone have a screenshot from Oleks that includes the explained variance bar chart?

**Comment by sheryjoe** [comment]
Screen Shot 2020-08-28 at 9 33 07 AM

**Comment by sheryjoe** [comment]
I think the new result has a more compact model.

**Comment by akenmorris** [comment]
Yeah, it looks that way.  There's not really any reason it should be any better though.  But it's not worse!

**Comment by cchriste** [comment]
> Yeah, it looks that way. There's not really any reason it should be any better though. But it's not worse!

1. is compact better? can you please describe how one can tell the difference?
2. one possible reason is we've improved image grooming, notably including a change that utilizes the true center of a pixel on a resample (apply transform) rather than the incorrect bottom-left-front corner of the pixel. This means that all the image grooming commands are not only more consistent (but watch out for linear vs nearest neighbor interpolation defaults), but also more correct.

**Comment by akenmorris** [comment]
> is compact better? can you please describe how one can tell the difference?

In general, yes.  The difference is shown in the bar chart.  You can see that the first mode of variation explains more of the variance in the data.

We don't have a baseline for the PR as this model was not possible before the PR.  But even then, I was trying to compare the result of my changes vs what Oleks had prior to my recent changes.

> one possible reason is we've improved image grooming

The femur mesh use case doesn't use any image grooming.

**Pull request merged**
