### PR TITLE
Add test for shape evaluation shapeworks subcommand

### LINKED ISSUE #602: add tests for Particle System shapeworks subcommands
The following commands need to have tests in Testing/shapeworksTests:
- read-particle-system
- compactness
- generalization
- specificity

### PR DESCRIPTION
**Pull request by medakk**
This PR adds a test for particle system subcommands in shapeworksTests.

Closes #602

### CODE REVIEW

**Comment by medakk** [comment]
Wait, I realized that the specficity command depends on random numbers, it won't work consistently across platforms. Is there an example of a shapeworksTest that checks whether the output(a single number) is "close to" something?

**Comment by medakk** [comment]
its quite a pain to do this in bash. i put a tiny python script in to compare the numbers.

**Review by archanasri — APPROVED** [review]

**Comment by sheryjoe** [comment]
@cchriste is this ready to merge?

**Comment by cchriste** [comment]
Merge is fine with me.
Karthik should be careful with those shell skills! 🤩

**Pull request merged**
