### PR TITLE
Use Case Documentation

### PR DESCRIPTION
**Pull request by jadie1**
This PR makes the use case documentation uniform and removes a lot of repetition.  All of the copy and pasted documentation that was the same for every use case is now only in "Getting Started with Use Cases" file (use-cases.md).
Addresses issues #1103 and #1347.

Each md file now contains the following sections:
- "What is the Use Case?" Describes what the use case demonstrates, what is different about it, and specifications on data
- "Grooming Steps" Describes grooming steps if any with visualization.
- "Supported Tags" Lists tags you can use with the use case
- "Optimization Parameters" Shows the dictionary of optimization parameters and specifies any choices unique to the use case.
- "Analyzing Shape Model" Displays and comments on expected output.

To review this PR you need to checkout the branch and run `mkdocs serve`. The videos on the sci server will not be visible via the github web interface.

### CODE REVIEW

**Comment by cchriste** [comment]
Can we please link all the related issues to the PR? In particular #1103 is linked to lots of other issues. Are these all taken care of with this PR?

**Comment by cchriste** [comment]
I have compiled and am reviewing the documentation. It _might_ help to update this section in order for reviewing to be inline with the instructions for doing so: http://sciinstitute.github.io/ShapeWorks/dev/docs.html.

**Comment by jadie1** [comment]
Issue #1103 is linked to all of the use case issues but this PR just
addresses the documentation, the use case issues will not be closed with
this PR.

I believe the two issues I linked are the only relevant ones.

**Comment by cchriste** [comment]
There are some missing resources, including simple gifs found on the SCI server (see https://github.com/SCIInstitute/ShapeWorks/pull/1470#issuecomment-923249238). Other resource found on the sci server are found just fine.

**Review by cchriste — CHANGES_REQUESTED** [review]
See comment on issue.

**Comment by sheryjoe** [comment]
Steps moving forward:
- Group use cases based on functionality/features demonstrated, e.g., meshes, segmentations, constraints, deep-learning, statistical-tests. This should happen at the docs level (creating subfolders for the use cases).
- Update examples.md to include this categorization and the new use cases. For each use case, we should highlight the feature(s) that are showcased in the use case (what makes it different).
- Add an introduction subsection to the use-case.md to introduce what is a use case in general, what is the workflow, add links to other documentations whenever applicable.

**Comment by sheryjoe** [comment]
Use Cases: 
<intro paragraph>
 <including link to create girder account>
 Running …
 Grooming … 
Arguments … 
Analyses …
 done!

**Comment by jadie1** [comment]
@sheryjoe @cchriste This should be ready to be reviewed again

**Comment by cchriste** [comment]
Wow! This is so much more understandable and worthwhile to users. 
 - femur mesh not done. Says coming soon. (another issue for this?)
 - how do you switch between datasets on multiple domains from mesh use case? It's also missing grooming, says coming soon.
 - supershapes: maybe link to or show the equation
 - shape statistics in python could link to Python API when we have docs for that (create issue and link to python api docs issue
 - Femur Shape Model Directly from Images should have link back to deep_ssm use case it mentions). Do they need to manually download data for this one?
 - right ventricle: is there an issue to finish it?

So a couple small changes, maybe some additional issues (so we don't forget), and merge!

**Comment by jadie1** [comment]
> * Femur Shape Model Directly from Images should have link back to deep_ssm use case it mentions). Do they need to manually download data for this one?

No it still automatically downloads. We are just noting that the data was generated by running the femur use case

**Comment by iyerkrithika21** [comment]
>  * femur mesh not done. Says coming soon. (another issue for this?)
>  * how do you switch between datasets on multiple domains from mesh use case? It's also missing grooming, says coming soon.

For all the mesh use cases, grooming will be added in the next release. Right now they run on pre-groomed data. 
We have this issue for it: https://github.com/SCIInstitute/ShapeWorks/issues/1386
The name in the multiple domain use case can be changed in the python code. There are comments and [print](https://github.com/SCIInstitute/ShapeWorks/blob/97e1d1e9908009417f4c6609ff3949de4f1f61ba/Examples/Python/ellipsoid_multiple_domain_mesh.py#L28) statements in the code to point to it
>   * shape statistics in python could link to Python API when we have docs for that ([Add reference documentation for our API  #1079](https://github.com/SCIInstitute/ShapeWorks/issues/1079))

Created: https://github.com/SCIInstitute/ShapeWorks/issues/1492

**Comment by cchriste** [comment]
> > * Femur Shape Model Directly from Images should have link back to deep_ssm use case it mentions). Do they need to manually download data for this one?
> 
> No it still automatically downloads. We are just noting that the data was generated by running the femur use case

Can this be made more clear in the documentation? All that needs to be added, probably to the data section early on, is what you just wrote.  Thanks!

**Comment by cchriste** [comment]
> The name in the multiple domain use case can be changed in the python code. There are comments and [print](https://github.com/SCIInstitute/ShapeWorks/blob/97e1d1e9908009417f4c6609ff3949de4f1f61ba/Examples/Python/ellipsoid_multiple_domain_mesh.py#L28) statements in the code to point to it

Will you please add a note to the beginning of the issue that clarifies this for the user? Thank you.

**Comment by jadie1** [comment]
> * right ventricle: is there an issue to finish it?
I am unclear on this use case... Looks like Archana added the documentation.
@archanasri is there an issue for the RV use case? Should we remove it from the doc for now?

**Comment by jadie1** [comment]
All of Cameron's suggested changes have been made. The right ventricle use case does not show up in the web doc (it's not in the yml) so I think it is okay to leave it.

I also added the note about windows visualization to the notebooks for issue #1113 

Should be ready to merge!

**Pull request merged**
