### PR TITLE
Fix #1869 - Optimize command not accepting .swproj files

### LINKED ISSUE #1869: Optimize command not accepting .swproj files

### PR DESCRIPTION
**Pull request by akenmorris**
Addresses:

* #1869

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
@akenmorris : Moksha and Zahid don't have their systems yet so I tried to run a use case on this branch by changing the extension of project name from ".xlsx" to ".swproj"
The optimization fails with the message: 
```
Error: [json.exception.type_error.302] type must be object, but is null

Called Process Error:
        Returncode: 1
        stdout: None
        stderr: None

```

**Comment by akenmorris** [comment]
Weird GHA error on only linux debug:

```
2022-09-22T22:56:16.7621383Z 3: Test command: /__w/ShapeWorks/ShapeWorks/build/bin/GroomTests
2022-09-22T22:56:16.7622002Z 3: Test timeout computed to be: 10000000
2022-09-22T22:56:16.8897133Z 3: Running main() from /home/conda/feedstock_root/build_artifacts/gtest_1647154636757/work/googletest/src/gtest_main.cc
2022-09-22T22:56:16.8898129Z 3: [==========] Running 1 test from 1 test suite.
2022-09-22T22:56:16.8899014Z 3: [----------] Global test environment set-up.
2022-09-22T22:56:16.8899682Z 3: [----------] 1 test from GroomTests
2022-09-22T22:56:16.8900227Z 3: [ RUN      ] GroomTests.basic_test
2022-09-22T22:56:16.9145662Z 3: unknown file: Failure
2022-09-22T22:56:16.9146578Z 3: C++ exception with description "/github/home/install/include/ITK-5.2/itkImageFileReader.hxx:133:
2022-09-22T22:56:16.9147385Z 3:  Could not create IO object for reading file ../shared/spheres/sphere30.nrrd
2022-09-22T22:56:16.9148049Z 3:   Tried to create one of the following:
```

**Comment by akenmorris** [comment]
> @akenmorris : Moksha and Zahid don't have their systems yet. So, I tried to run a use case on this branch by changing the extension of project name from ".xlsx" to ".swproj" The optimization fails with the message:
> 
> ```
> Error: [json.exception.type_error.302] type must be object, but is null
> 
> Called Process Error:
>         Returncode: 1
>         stdout: None
>         stderr: None
> ```

Can you tell me where you are changing this?

**Comment by iyerkrithika21** [comment]
> > @akenmorris : Moksha and Zahid don't have their systems yet. So, I tried to run a use case on this branch by changing the extension of project name from ".xlsx" to ".swproj" The optimization fails with the message:
> > ```
> > Error: [json.exception.type_error.302] type must be object, but is null
> > 
> > Called Process Error:
> >         Returncode: 1
> >         stdout: None
> >         stderr: None
> > ```
> 
> Can you tell me where you are changing this?

https://github.com/SCIInstitute/ShapeWorks/blob/bede4502ba953bae85b6c0ce20dfbcd694acf486/Examples/Python/ellipsoid.py#L204

**Comment by akenmorris** [comment]
Should be fixed now, @iyerkrithika21

**Comment by iyerkrithika21** [comment]
> Should be fixed now, @iyerkrithika21

Works now! Thanks!

**Pull request merged**
