### PR TITLE
Restore old CWD before writing project file

### LINKED ISSUE #1232: shapeworks optimize --name project_file.xlsx crashes at end
`shapeworks optimize --name Output/ellipsoid_mesh/ellipsoid-v0/meshes/test.xlsx`

```
Verbosity 0: This will be the only output on your screen, unless there are any errors. Increase the verbosity if needed.
ApplyConstraintsToZeroCrossing 15
Error writing xlsx: xlnt::exception : bad zip stream, 
terminate called after throwing an instance of 'char const*'
fish: “../../build/cmake-build-release…” terminated by signal SIGABRT (Abort)
```
^this happens at the end of optimization

Everything works fine in Studio: the error is only when running from the command line. Here's the stack trace:

```
__GI_raise 0x00007f2167d8afb7
__GI_abort 0x00007f2167d8c921
__gnu_cxx::__verbose_terminate_handler 0x00007f216822c892
__cxxabiv1::__terminate 0x00007f216822af69
std::terminate 0x00007f216822afab
__cxxabiv1::__cxa_throw 0x00007f216822b194
shapeworks::Project::save Project.cpp:93
shapeworks::OptimizeCommand::execute Commands.cpp:92
shapeworks::Command::run Command.cpp:27
shapeworks::Executable::run Executable.cpp:94
shapeworks::Executable::run Executable.cpp:128
main shapeworks.cpp:96
__libc_start_main 0x00007f2167d6dbf7
_start 0x0000557955bd934a
```

(this is on XLNT 1.4. I haven't rebuilt dependencies yet)

### PR DESCRIPTION
**Pull request by medakk**
Closes #1232

### CODE REVIEW

**Comment by medakk** [comment]
@akenmorris 
Particle files are being written to the root directory of the XLSX, and not the project_file_particles/ scheme that was introduced in the multi domain PR, when running `shapeworks optimize --name project_file.xlsx`. I'm not sure if I've caused this issue with this PR, or it was never implemented

**Review by akenmorris — APPROVED** [review]

**Comment by akenmorris** [comment]
Looks good.  I believe I fixed the issue you mentioned, please check and we will merge.

**Comment by medakk** [comment]
Thanks! It writes to the correct folder now

 I'm still seeing the "Tab" issue when going from the number of particles to the other hyperparameters.

image

after pressing tab, the focus disappears. Doesn't go to initial relative weighting

**Comment by akenmorris** [comment]
Ah yes, multiple domains.

**Pull request merged**
