### PR TITLE
Studio Updates

### PR DESCRIPTION
**Pull request by akenmorris**
This PR addresses:

* #254 
* #1674 
* #547

Also fixes for:

* #1739 
* #1735
* #1734 

image

image

image

Difference to mean (for any shape, e.g. sample, pca mode position):

image

https://user-images.githubusercontent.com/1693349/164534628-343867bc-e4af-43e0-bec1-aa814708bc60.mp4

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
@akenmorris: I am unable to export the montage. Not sure if this is a problem with my build or system. 

The montage is generated and I am able to change things in the window but when I say export, I see this error on the command line, and the image is not saved.
```
inotify_add_watch(/home/sci/iyerkrithika/ShapeWorks_new/Testing_PRS) failed: (No space left on device)

```
image

**Comment by akenmorris** [comment]
Does it bring up a file chooser when you click `Export`?  

I assume your disk is not actually full?  (though it said `No space left on device`)

**Comment by iyerkrithika21** [comment]
Other things seem great to me. I was able to test most of the issues this PR is addressing. 
Could not test the issue with landmark scrolling. What would be the correct way to test it?

**Comment by iyerkrithika21** [comment]
> Does it bring up a file chooser when you click `Export`?
> 
> I assume your disk is not actually full? (though it said `No space left on device`)

Yes, the file/folder selection does show up. I can enter a name and click on export. 
The disk is not full.

**Comment by akenmorris** [comment]
> Could not test the issue with landmark scrolling. What would be the correct way to test it?

It's a bit tricky.  I think it'd be best merge and get a dev build for Penny to try.

**Comment by akenmorris** [comment]
Here's something about that inode message:

https://askubuntu.com/questions/1088272/inotify-add-watch-failed-no-space-left-on-device

`The error message doesn't actually refer to the amount of storage space, but to the amount of inotify watches that are available for a given file system (see also here: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers).`

Seems very weird.  Are the other export options working?

**Comment by iyerkrithika21** [comment]
I tried exporting PCA particles, and that worked.

**Comment by iyerkrithika21** [comment]
Exporting PCA scores didn't work 
I saw the link you shared, and there they suggest some changes for which I need root access. 
I might have to contact the support to try that. Meanwhile, @jadie1, can you try exporting the montage? 
It looks like a problem with my system rather than the build.

**Comment by akenmorris** [comment]
Can you try again, I've made some changes.  I think on Linux it wasn't getting a default extension and it didn't know how to save it.  I've also added a message either in the statusbar (success) or an error dialog.

I think that message you saw on the console is just warning and nothing to do with it not saving.

**Comment by iyerkrithika21** [comment]
image
Yup, that fixed it!

**Comment by iyerkrithika21** [comment]
@akenmorris: 
1. All the exports work correctly. Export current mesh and export mesh scalars fail for peanut shared boundary use case. 
image
This might be because we don't have any reconstruction for the contour domains.
2. For other datasets, the mesh isn't saved unless we provide an extension for export mesh. Is this intentionally done?
3. Mesh scalars also requires an extension in the name; it does save the scalar as a text file without extension.

**Comment by akenmorris** [comment]
Yes, the issue with the peanut shared boundary use case is that we don't have a contour reconstruction method yet.  At the moment it's probably better to have the export fail than to save an empty mesh for that domain.

**Comment by akenmorris** [comment]
Anything else needed to merge?  @iyerkrithika21 ?

**Comment by iyerkrithika21** [comment]
> Anything else needed to merge? @iyerkrithika21 ?

Looks good! 
- Saving mesh and scalar are working as expected now. 
- Skipping groom for contour also works

**Review by jadie1 — APPROVED** [review]
Everything I tried worked as expected!
image

**Review by iyerkrithika21 — APPROVED** [review]

**Pull request merged**
