### PR TITLE
Delete ParticleClipRegionDomain

### PR DESCRIPTION
**Pull request by 0leks**
It was nearly identical to ParticleRegionDomain, its superclass...

### CODE REVIEW

**Comment by akenmorris** [comment]
Seems fine.  What was different?

**Comment by 0leks** [comment]
ClipRegion was using GetUpperBound() to get the bounds, Region was accessing the variable directly.

**Comment by akenmorris** [comment]
Thanks.

**Comment by sheryjoe** [comment]
Is this a renaming of ParticleClipRegon to ParticleRegion? I am not seeing other differences?

**Comment by 0leks** [comment]
No this is deleting ParticleClipRegion because it inherits from ParticleRegion and is identical to ParticleRegion

**Pull request merged**
