### PR TITLE
Executable resample

### PR DESCRIPTION
**Pull request by archanasri**

### CODE REVIEW

**Comment by akenmorris** [comment]
Looks like there is an unresolved conflict in GroomUtils.py

   File "/home/runner/work/ShapeWorks/ShapeWorks/Examples/Python/GroomUtils.py", line 58
4:     <<<<<<< HEAD

**Comment by akenmorris** [comment]
Are we going to merge this into master after this merge?

**Comment by archanasri** [comment]
> Are we going to merge this into master after this merge?

Yes

**Comment by akenmorris** [comment]
I see there are more conflicts.  I'm not quite sure how to resolved them:

def applyCOMAlignment(parentDir, inDataListSeg, inDataListImg, processRaw=False):
=======
def applyCOMAlignment(outDir, inDataListSeg, raw=[]):
>>>>>>> origin/master

Should we use what's in master or is this updated in executable?

**Comment by archanasri** [comment]
> I see there are more conflicts. I'm not quite sure how to resolved them:
> 
> # def applyCOMAlignment(parentDir, inDataListSeg, inDataListImg, processRaw=False):
> def applyCOMAlignment(outDir, inDataListSeg, raw=[]):
> 
> > > > > > > > origin/master
> 
> Should we use what's in master or is this updated in executable?

Yeah, I am trying to resolve the conflicts. We should be using what's in the master.

**Pull request merged**
