### PR TITLE
Remove std::map from ParticleContainer

### PR DESCRIPTION
**Pull request by medakk**
Replaces std::map in ParticleContainer with std::vector, results in faster optimization(femur_mesh in 38 minutes vs 50 minutes). Tested on ellipsoid(image domain), works correctly there.

Note that this builds on the cachewhichtri branch, so the PR diff looks huger than it really is. See https://github.com/SCIInstitute/ShapeWorks/compare/cachewhichtri...particlecontainer for the changes

Specifically, note the [removal of the Erase function](https://github.com/SCIInstitute/ShapeWorks/compare/cachewhichtri...particlecontainer#diff-f16703aff672f1a54739e4c2cedc11271f53075609dea00ba557574b64e03bbfL131) and the [removal of its usage in ParticleNeighborhood](https://github.com/SCIInstitute/ShapeWorks/compare/cachewhichtri...particlecontainer#diff-0b01cf01f36bdccbd15ce6edc67286dc3fe97f6e161f75d9cfca4311909f32beL150). This has not caused any problems in the testing I've done so far, but please let me know if there is some unintended consequence of that.

### CODE REVIEW

**Comment by akenmorris** [comment]
> Specifically, note the removal of the Erase function 

Yeah, don't worry about that.  Back when there was ShapeWorksShop, you could probably interactively remove a particle, but this is not a thing anymore.

**Comment by akenmorris** [comment]
Very nice.  Is there any performance improvement?

**Comment by medakk** [comment]
Yes, femur_mesh went from 50 minutes(this is with the triangle caching stuff) to 38 minutes

The femur use case went from ~2 hours to 1:35 hours.

**Comment by akenmorris** [comment]
What effect did just the map stuff have?  I thought the 50->38 was just the triangle stuff.

**Comment by medakk** [comment]
For femur_mesh,
Triangle caching: 1:35 hours to 50 minutes
Remove std::map: 50 minutes to 38 minutes

**Comment by medakk** [comment]
Oh, what I mean is that it takes 50 minutes with just the triangle changes, and 38 minutes with the triangle+map changes

**Comment by sheryjoe** [comment]
@medakk is there any improvements with image domains?

**Comment by medakk** [comment]
Yes,  femur image domain went from ~2 hours to 1:35 hours.

**Review by akenmorris — APPROVED** [review]

**Comment by akenmorris** [comment]
Hey @medakk , can you take a look at the conflicts?  I merged the triangle branch and I thought this one was based on it.

**Comment by medakk** [comment]
Very weird, I merged in master (e2f45273004d73bff37e35b4489e15212208507b) and it had no changes to any files, but the merge conflict disappeared. (also the diff shown on GitHub was wrong earlier, now it shows the correct diff)

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
