### PR TITLE
Studio Updates

### PR DESCRIPTION
**Pull request by akenmorris**
This PR addresses the following issues:

#1452 - Opacity controls for each domain
#1284 - Feature Request - Multi-domain transparency
#1359 - Add support for manual feature scalar range
#1448 - Studio: Recent XML projects need to store path as well
#1159 - Studio: Allow passing in initial points
#1401 - Extra space in optimize params in studio 

@patkins, Support for initial points is limited to the running of optimization, there is no display of these points yet.  To use this features, simply add a column with the prefix "landmarks_file_<name>" and these points will be used as the initial points to the optimizer.

For example:

image

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
> I also could not find the transparency controls for multi-domain models.

@patkins this option is available is when you click on the drop-down arrow next to the ISO button at the bottom of the Studio window

**Comment by akenmorris** [comment]
Yeah, the opacity controls are on the little dropdown like the glyph size and detail.

For the naming if <file> is your name, then the landmarks column will need to be landmarks_file_file.  I specified "file" in the name because I intend to store landmarks directly in the spreadsheet for landmarks creating within studio so as to not write out N more files.  Sorry if it's confusion.  I would do something like:


| shape_labrum      | landmarks_file_labrum |
| ----------- | ----------- |
| ...      | ...       |
| ...   | ...        |

**Review by iyerkrithika21 — APPROVED** [review]
I was able to test all the changes, and they seem to be working fine.

**Comment by patkins** [comment]
I now see the opacity and the landmarks file seems to be importing correctly.

**Pull request merged**
