### PR TITLE
Transforms python api

### LINKED ISSUE #1276: Replace proprietary Transform type with Eigen matrix in Python bindings
Currently we bind an opaque itk::Transform to the Transform type in Python.
This can be passed back and forth (thereby enabling it to be modified on the Python side) by sending a transparent Eigen matrix, like we already do with most other similar thing such as Image.coordsys, the Eigenvectors of ParticleShapeStatistics, etc. 

Let's do the same thing with Transform, either passing it as a 3x4 or 4x3 or (more common in graphics) 4x4 [right-handed] matrix incorporating rotation, scaling, shear, and translation. 

This task should include providing examples of using the transforms in a Jupyter notebook.

### LINKED ISSUE #1493: fix Mesh.create/applyTransform Python bindings
`Mesh.createTransform` returns an invalid Python type. It should simply return a 4x4 `numpy` array, similarly to the way `Image.createTransform` returns a 3x3 `numpy` array.*

- [x] The Python binding for `Mesh.applyTransform` should accept such an array.

- [x] Documentation for these functions is also lacking and should be improved as in Image.create/applyTransform (C++ header, Python description in ShapeworksPython.cpp, and `shapeworks` command line commands). 

- [x] Unit tests should also be added.

- [x] NOTE: these functions aren't apparently used in any use cases (or unit tests, tsk tsk). It seems very useful, just as the Image versions. We might consider using them in one of our Mesh-based use cases.
       - added Jupyter notebook

- [x] *once #1276 is finished

### PR DESCRIPTION
**Pull request by cchriste**
`createTransform` has been split into `createCenterOfMassTransform` and `createRigidRegistrationTransform`.
A new opaque type called WarpTransform has been added to the Python module to be used for those, but `applyTransform` still works for their application with overloading. 

For Meshes, create and apply transforms now use numpy arrays as well. 

Added Jupyter notebooks demonstrating their use.
Screen Shot 2021-11-05 at 9 59 08 PM

Screen Shot 2021-11-06 at 3 29 40 PM

closes #1276
closes #1493

### CODE REVIEW

**Comment by cchriste** [comment]
@akenmorris I removed you from reviewers, but feel free to give it a glance if you want. Thanks for your help over Slack on the compile warnings.

**Review by jadie1 — APPROVED** [review]
I tried the notebooks and checked the use cases and tested some numpy transforms, looks like everything is working as expected!

**Comment by akenmorris** [comment]
Is this for 6.2 or 6.3?

**Comment by cchriste** [comment]
> Is this for 6.2 or 6.3?

6.3 afaik

**Review by archanasri — APPROVED** [review]

**Comment by cchriste** [comment]
> > Is this for 6.2 or 6.3?
> 
> 6.3 afaik, although mesh transforms are simply broken in the current code, so one could argue it's necessary for 6.2.

@sheryjoe I propose we add this to 6.2. Some developer users are asking for ways to create and use transforms on Meshes, and the Python bindings are actually broken in 6.2.

**Comment by sheryjoe** [comment]
@cchriste let's add it to 6.2 @archanasri please update the release notes accordingly.

**Pull request merged**
