### PR TITLE
Pytorch

### PR DESCRIPTION
**Pull request by jadie1**
This PR attempts to address issue #876 
Ultimately we decided it is best if we continue to just support the most recent release of PyTorch but add some documentation describing what to do if is not compatible with someone's CUDA version or if `nvidia-smi` does not correctly detect the CUDA version.

I added CUDA 11.0 to the list because it is now supported as can be seen here: [pytorch.org](https://pytorch.org/)

The documentation has been added on the mkdocs branch here: [pytorch-gpu.md](https://github.com/SCIInstitute/ShapeWorks/blob/mkdocs/docs/deep-learning/pytorch-gpu.md)

### CODE REVIEW

**Comment by akenmorris** [comment]
Looks fine to me.  There seem to be a bunch of conflicts if you check the linux build log.

**Comment by jadie1** [comment]
I think it's because I actually called the install_pytorch function. It's been removed in the master branch

**Comment by akenmorris** [comment]
Makes sense.  Now how to resolve the conflict?

**Comment by jadie1** [comment]
@akenmorris  Looks like it built with pip!

**Review by iyerkrithika21 — APPROVED** [review]

**Pull request merged**
