### PR TITLE
Rescale update vector to original magnitude after projection to surface tangent

### PR DESCRIPTION
**Pull request by akenmorris**
This is something I discussed with @prafulag.

The goal here is to restore the original update vector magnitude while still projecting to the tangent plane.

This is not ready to merge, but I'm making the PR for people to look at it.

We may need to adjust the number of iterations on some of the use cases.

### CODE REVIEW

**Comment by sheryjoe** [comment]
This makes sense to me. I assume this could reduce the number of iterations. It is worth running some benchmarks to assess this hypothesis.

**Comment by akenmorris** [comment]
Yes, it should restore the previous speed of particle spread.

I will have to experiment with all of the use cases to adjust the iterations.

**Comment by prafulag** [comment]
I am certainly curious to know if that improves speed. Thanks Alan for taking this on.

Regards,
Praful Agrawal

**Comment by sheryjoe** [comment]
@akenmorris are we still planning to merge this?

**Comment by akenmorris** [comment]
Eventually, yes.  It's going to require a lot of testing and likely re-tuning of all of the use cases.

**Comment by medakk** [comment]
@sheryjoe  I don't believe we intend to merge this branch. The rescaling for meshes has already been merged to release. I tested that and it works well.

**Comment by akenmorris** [comment]
@medakk , correct.  @sheryjoe , this requires more testing for image based optimization.

**Comment by akenmorris** [comment]
Close for now.

**Pull request closed without merging**
