### PR TITLE
Fix issues 1800, 1815

### PR DESCRIPTION
**Pull request by akenmorris**
This PR fixes:

* #1800 
* #1815

### CODE REVIEW

**Comment by HeavenlyBerserker** [comment]
Gives a weird error when I try without groomed data. For instance, "optimize (copy).xlsx" where I removed the groomed column gives the following error

`Error: Project failed to load: xl/worksheets/sheet3.xml:2:3053: error: unexpected attribute 'aca'`

This happens in the FFC directory as well. It's especially strange cause there is no aca attribute to my knowledge. Is this because of LibreOffice Calc corrupting xlsx? I'm not getting "No groomed inputs for optimization" at all. 

[sphere.zip](https://github.com/SCIInstitute/ShapeWorks/files/9041412/sphere.zip)

**Comment by akenmorris** [comment]
Seems to be an issue with XLNT:

https://github.com/tfussell/xlnt/issues/473

**Comment by HeavenlyBerserker** [comment]
Ok, so I've rewritten my xml_to_xlsx code to use the python API for Project, so I can avoid the XLNT thing. In here, it creates the optimize2.xlsx file, but it seems to get stuck loading the project. Is it because the "alignment_1" column is blank?

[ffc.zip](https://github.com/SCIInstitute/ShapeWorks/files/9079492/ffc.zip)

**Comment by akenmorris** [comment]
@HeavenlyBerserker , it's "hanging" in the dijkstra shortest path code, at least when I paused it in the debugger after some time.

Merging in the PR #1825 , it no longer hangs, but gives some error in vtkSelectPolyData.  Are you sure this project has valid constraints?

**Pull request merged**
