### PR TITLE
Contour image generation

### PR DESCRIPTION
**Pull request by jadie1**
This PR addresses issue #1197 - adding the option of seg and image generation for 2D supershapes generation.

To test:

- Add shapely to shapeworks conda environment
- Run pip install ShapeWorks/Python/ShapeCohortGenPackage/
- Generate 2D supershapes with images in python the same way we do 3D, for example:

> ```
> import ShapeCohortGen
> 
> out_dir = "Generated_Contours/"
> ss_generator = ShapeCohortGen.Supershapes2DCohortGenerator(out_dir)
> contourFiles = ss_generator.generate(3)
> segFiles = ss_generator.generate_segmentations()
> imageFiles = ss_generator.generate_images()
> ```

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
@jadie1 are the images expected to look this way?

**Comment by jadie1** [comment]
@iyerkrithika21 thanks, it should work now

**Comment by iyerkrithika21** [comment]
Image generation works fine now.
Should we include these functions in the shape cohort notebook?

**Comment by jadie1** [comment]
> Should we include these functions in the shape cohort notebook?

I'm not sure, the ellipsoid joints are not in the notebook either, Maybe we should include a description of the other types of shapes you can generate but not walk through it. Since the process is the same regardless of the kind of shape, I think walking through just supershapes and ellipsoids is sufficient. What do you think?

**Comment by iyerkrithika21** [comment]
> > Should we include these functions in the shape cohort notebook?
> 
> Maybe we should include a description of the other types of shapes you can generate but not walk through it. 
This sounds good

**Review by iyerkrithika21 — APPROVED** [review]

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
