### PR TITLE
DeepSSM Updates

### PR DESCRIPTION
**Pull request by jadie1**
This PR addresses:

- Issue #1105 Refactoring DeepSSM to use a config file
- Issue #1223 Fixing surface to surface distance in eval
- Updates getting meshes from distance transforms to use pybind `toImage()` instead of command line `MeshFromDistanceTransforms`
- Updates getting meshes from particles to use `mesh-warp` instead of `ReconstructSurface`
- Updates use case to print warning but still run on CPU rather than exiting
- Improves the tiny test so it runs in about 2 min

To test, run the tiny test or the full use case (both should run on GPU or CPU). 
This will probably require running:
 `pip install Python/DeepSSMUtilsPackage/` 
`pip install Python/DataAugmentationUtilsPackage/`

### CODE REVIEW

**Comment by akenmorris** [comment]
Looks pretty good.  In order to use deep_ssm --tiny_test with the github actions, we will need to turn off all the displays.  Right now it's bringing up the violin plot and this will hand on the Windows GH.  What do you think?

**Comment by akenmorris** [comment]
It's very possibly I've done something wrong (I did do the two pip installs), but it's hanging for me, using no CPU after it brought up the violin plot.  On the console, I see:
```

********************* WARNING ****************************
Pytorch is running on your CPU!
This will be very slow. If your machine has a GPU,
please reinstall Pytorch to your shapeworks conda
environment with the correct CUDA version.
**********************************************************
Loading data loaders...
Done.
Defining net...
Done.
Beginning training on device = cpu

Epoch	  LR	  Train_Err	  Train_Rel_Err	  Val_Err	  Val_Rel_Err	  Sec
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:206] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
```

**Comment by jadie1** [comment]
> Looks pretty good. In order to use deep_ssm --tiny_test with the github actions, we will need to turn off all the displays. Right now it's bringing up the violin plot and this will hand on the Windows GH. What do you think?

Okay, I will fix it so the plot is not displayed for the tiny_test

**Comment by jadie1** [comment]
Are you running on mac? I am not seeing this CPU error on linux.... I'll try to look into it.

**Comment by akenmorris** [comment]
Yeah, Mac. I am going to try on another Linux machine. Waiting for conda to “solve” the environment.

**Comment by jadie1** [comment]
@akenmorris Looks like this is a mac problem and the solution is to not use parallel computing: https://stackoverflow.com/questions/64772335/pytorch-w-parallelnative-cpp206

**Comment by akenmorris** [comment]
Yeah, setting OMP_NUM_THREADS=1 fixes it.  Should we set that env var in the use case for Mac?

**Comment by jadie1** [comment]
Yeah that sounds good. So should I just add this to the use case:
```
if platform.system() == "Darwin":
	os.system("export OMP_NUM_THREADS=1")
```

**Pull request merged**
