### PR TITLE
Consolidated shapeworks executable and five commands (so far)

### PR DESCRIPTION
**Pull request by cchriste**
This includes the framework for the consolidated executable with classes Executable, Command (and subclasses ImageCommand, MeshCommand, MultiImageCommand), Commands (with specific commands subclassed from this), as well as classes comprising the actual functionality of the original standalone executables, including (so far) Image and a rough draft of Mesh. 

Working notes are found in Applications/shapeworks/notes.txt and these include instructions for starting a new command, testing it, and a list of all the extant commands along with notes for each that has been converted so far. 

Finally, there are some improvements to the Python examples, such as the simplification of functions in GroomUtils. These can be emulated to improve the maintainability of examples moving forward.  

There are still plenty to convert, but these changes have been thoroughly tested and will help guide the overall organization of the framework moving forward. For example, the actual classes in the Libs folders rather than individual executables, with which other tools can start to build. 

The next steps that will be relatively straightforward will be to enable the rest of the grooming functionality to be accessible via these new classes. Another valuable step will be to break down the monolithic ShapeWorksRun executable into functions of the new class Optimize.

### CODE REVIEW

**Comment by akenmorris** [comment]
Have you looked at why the Github Actions are failing?

**Comment by cchriste** [comment]
There have been suggestions for improvements, but this branch to still be fully functional without them and it's a work in progress so incremental improvements will be ongoing. How do we feel about merging this today?

**Comment by akenmorris** [comment]
I hope you don't mind, I turned on file compression on image output.  This makes the difference of 500kb mask nrrds vs 150MB.

**Comment by cchriste** [comment]
👍

**Pull request merged**
