### PR TITLE
Studio constraints

### PR DESCRIPTION
**Pull request by akenmorris**
This PR adds comprehensive support for plane constraints to Studio and to the project spreadsheet in the form of a pointer to a new JSON file format for constraints.

studio_plane_constraints

### CODE REVIEW

**Comment by jadie1** [comment]
@akenmorris could you share an example json file?

**Comment by akenmorris** [comment]
Sure:

```
{
    "planes": [
        {
            "points": [
                [
                    -33.99237185904836,
                    2.732385773314178,
                    105.06661377816961
                ],
                [
                    -39.23297577029964,
                    -1.0988468012974977,
                    105.74199803849412
                ],
                [
                    -45.8492894604039,
                    -4.155598040538237,
                    105.24729999228116
                ]
            ]
        }
    ]
}%
```

**Review by jadie1 — APPROVED** [review]
Working now on this example: /home/sci/jadie/Public/femur_planes.zip

**Review by HeavenlyBerserker — APPROVED** [review]
@akenmorris Based on the diffs and from what I can understand, it all seems to be in order. Thanks for cleaning up my code, BTW.

@jadie1 Is femur_planes the future replacement for the femur_cut use case? 

I don't see any issues with this, and as long as Jadie's femur_planes works, this should be good to merge. Good job, Alan!

**Comment by jadie1** [comment]
@HeavenlyBerserker it's just a small example with the femur tiny test meshes, but yes it proves we will be able to replace femur_cut planes with json format. Might just need to add further spreadsheet pybindings first.

**Pull request merged**
