### PR TITLE
Use case tiny test and subsampling

### PR DESCRIPTION
**Pull request by jadie1**
Updated use cases to:
- Include a tiny test which always runs on the first 3 shapes (issue #789)
- Include the option to run on a subset of the shapes based on clustering on segs or meshes (issue #790)
- Updated documentation on mkdocs branch to specify these options are necessary in new-use-case.md 

The only use case which does not have these options is the ellipsoid fixed domains because these options don't make sense in that context. 

To test tiny_test run:
`python RunUseCase.py --use_case <use_case> --tiny_test`

To test subsampling run:
`python RunUseCase.py --use_case <use_case> --use_subsample --num_subsample <integer>`
(Defaults to 3 if `num_subsample` is not specified)

### CODE REVIEW

**Comment by akenmorris** [comment]
What do you think about combining the two options `--use_subsample` and `--num_subample <integer>`

Unless the default of 3 is somehow very useful, it seems the user would typically always specify both.

**Comment by jadie1** [comment]
We just added this in PR #784 
@sheryjoe do you have thoughts on this?

**Comment by sheryjoe** [comment]
--num_subample should be --num_subsample

**Comment by jadie1** [comment]
It is --num_subsample in the code, sorry that was just a typo in the pull request. I'll fix it

**Comment by sheryjoe** [comment]
> We just added this after some discussion in PR #784
> @sheryjoe do you have thoughts on this?

There is merit in both ways. Combining them into one argument (e.g. --use_subsample <optional num of samples, int>) is more compact, and having them as separate is more descriptive. I am fine with either.

**Pull request merged**
