### PR TITLE
pymodule

### PR DESCRIPTION
**Pull request by archanasri**
This branch needs testing:
1. Check if the notebooks are producing correct results
2. Check if any cell or combinations of cells can be just added as helper function or removed
3. Read through markdown text to see if it can be removed or paraphrased to reduce verbosity

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
Please make changes to this branch [pymodule_nb_changes](https://github.com/SCIInstitute/ShapeWorks/tree/pymodule_nb_changes) so that the GitHub actions are not triggered for each new commit made to this PR.

I created a new notebook for jupyter notebook shortcuts and resources so that we don't repeat this in every notebook.

**Comment by cchriste** [comment]
Linux build error:

**Comment by jadie1** [comment]
I am getting this error with the sw.plot_volumes() function in getting-started-with-shape-cohort-generation.ipynb
image

**Comment by jadie1** [comment]
@Archana, @iyerkrithika21 and I have been refactoring the use cases and notebooks on the `pymodule_nb_changes` branch which is branched off of this.  We will make a PR for that today or tomorrow. Do you think we should test and merge this PR first? Or should we use the  `pymodule_nb_changes` PR instead of this? I'm just not sure all the notebooks and use cases are working on the `pymodule` branch but we know they are on `pymodule_nb_changes`. Let us know what you think

**Comment by cchriste** [comment]
> @archana, @iyerkrithika21 and I have been refactoring the use cases and notebooks on the `pymodule_nb_changes` branch which is branched off of this. We will make a PR for that today or tomorrow. Do you think we should test and merge this PR first? Or should we use the `pymodule_nb_changes` PR instead of this? I'm just not sure all the notebooks and use cases are working on the `pymodule` branch but we know they are on `pymodule_nb_changes`. Let us know what you think

I would suggest we still use the pymodule _pull request_, but keep working on this branch. @archanasri and I did this with pybind and pybind_work, occasionally pushing to the one attached to the pull request in order to ensure things were compiling and running on all platforms. 

Let's also delete all the other pymodule_* branches if they're not being used.

**Comment by sheryjoe** [comment]
@jadie1 @riddhishb @iyerkrithika21 can you finalize your review ASAP?

**Comment by akenmorris** [comment]
@jadie1 , can you look at the deep_ssm.py conflicts?  It's a little confusing because it appears pymodule's version has conflict markers from a merge with pybind branch that were never resolved (and instead committed?) @archanasri @cchriste ?

**Comment by jadie1** [comment]
@akenmorris I'll look into that now

**Comment by cchriste** [comment]
> @jadie1 , can you look at the deep_ssm.py conflicts? It's a little confusing because it appears pymodule's version has conflict markers from a merge with pybind branch that were never resolved (and instead committed?) @archanasri @cchriste ?

The deep_ssm.py conflict looks like it has nothing to do with pybind itself, but from a merge on May 25 that may have implicitly included a merge from master.

**Comment by cchriste** [comment]
We were close on the working tests using the module, but not quite there (as can be seen from all the "shapeworks module not found" errors in the GitHub actions. I'm looking into this now.

**Comment by cchriste** [comment]
I'm currently addressing the other merge conflicts. I would very much like to take a shot at fixing the tests (details here: https://github.com/SCIInstitute/ShapeWorks/pull/1181/checks?check_run_id=2750625849) and include that in the next push. Thoughts welcome! In particular  the bash scripts for shapeworksTests (the command line) can’t be found. Regardless of the PATH, LD_LIBRARY_PATH, and PYTHONPATH changes (summary: system setting for these is now put before the defaults provided in Testing.cpp), why would this be occurring?

**Pull request merged**
