### PR TITLE
6.2 Release notes

### PR DESCRIPTION
**Pull request by sheryjoe**

### CODE REVIEW

**Comment by akenmorris** [comment]
Any reason this PR has a few scattered code changes?  Was it branched from master?

**Review by iyerkrithika21 — APPROVED** [review]
In femur-pvalues.md, the link should be changed to: 
`[Femur: SSM from Meshes](../mesh-based/femur.md)`

Everything else looks good.

**Comment by akenmorris** [comment]
Yes, @jadie1 , I see that as well.  There were spaces between the [...] and (link).

But another problem I see is that these links are absolute links rather than relative.  This is actually what we need for the github release page and email, but wrong for being inside the mkdocs.

**Comment by sheryjoe** [comment]
Agreed. @archanasri can you fix the absolute links in release_notes.md? these should be relative to our docs directory.

**Comment by archanasri** [comment]
> Agreed. @archanasri can you fix the absolute links in release_notes.md? these should be relative to our docs directory.

I have fixed it.

**Review by jadie1 — APPROVED** [review]

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
