### PR TITLE
DeepSSM early stopping

### PR DESCRIPTION
**Pull request by jadie1**
This pull request covers issue #807 and fixes some bugs.

Bugs:

- There is an error from PR #785 where when percent variability is specified instead of number of dims for PCA in augmentation, then we don't have access to the number of PCA dims for initializing a model in testing. I fixed this by having the data augmentation call return the number of dimensions used. 
- For KDE sampling in data aug, sigma needed to be divided by the number of dims.
- When getting the mean and standard deviation for PCA score whitening, needed to be vector not single value. 

To test the early stopping:

- Checkout DeepSSM branch 
- Rerun conda_installs or with the shapeworks environment activated run `pip install /ShapeWorks/Python/DeepSSMUtilsPackage/` and  `pip install /ShapeWorks/Python/DataAugmentationUtilsPackage/`
- From 'Examples/Python/' run: `python RunUseCase.py --use_case deep_ssm --tiny_test`
- Check to see that is saves best and final model

### CODE REVIEW

**Comment by jadie1** [comment]
Can we merge this?

**Comment by iyerkrithika21** [comment]
I keep encountering the libffi.so.6 issues here.
As suggested by @akenmorris I link the libffi.so.6 to libffi.so.7. I also ran ls -la /path/to/anaconda/envs/shapeworks/lib | grep libffi to make sure the link was made. 
The link goes aways after I run conda_installs.sh

**Comment by iyerkrithika21** [comment]
@medakk can you try to build this branch and see if you can reproduce the conda libff error?

**Comment by medakk** [comment]
I pulled the branch and ran conda_installs.sh (just using a different environment name than the default "shapeworks"). The install completed fine. I don't have libffi6:

```
$ ls -lhta /scratch/karthik/miniconda3/envs/sw_deepssm_branch/lib/ | grep libffi
lrwxrwxrwx  1 karthik karthik   15 Dec 15 17:01 libffi.so -> libffi.so.7.1.0
lrwxrwxrwx  1 karthik karthik   15 Dec 15 17:01 libffi.so.7 -> libffi.so.7.1.0
-rwxrwxr-x  3 karthik karthik  50K Dec  7 07:40 libffi.so.7.1.0
-rw-rw-r--  3 karthik karthik  66K Dec  7 07:40 libffi.a
```

I'm on Ubuntu 18.04 with conda 4.9.2


@iyerkrithika21
> The link goes aways after I run conda_installs.sh

That's odd, do we have some command in the installs that clears the environment? In any case, it appears that the error stems from just the pip installs for ShapeWorks utilities(judging by the screenshot you sent on slack earlier). Try this:
* delete the conda environment
* run conda_install.sh till it crashes
* link libffi as required
* run just the pip install commands in your shell:

```
pip install Python/DatasetUtilsPackage
pip install Python/DocumentationUtilsPackage
pip install Python/DataAugmentationUtilsPackage
pip install Python/DeepSSMUtilsPackage
```

**Comment by iyerkrithika21** [comment]
@medakk  This is what I did. I didn't just delete the environment, I uninstalled miniconda as well.
> That's odd, do we have some command in the installs that clears the environment? In any case, it appears that the error stems from just the pip installs for ShapeWorks utilities(judging by the screenshot you sent on slack earlier). Try this:
> 
>     * delete the conda environment
> 
>     * run conda_install.sh till it crashes
> 
>     * link libffi as required
> 
>     * run just the pip install commands in your shell:
> 
> 
> ```
> pip install Python/DatasetUtilsPackage
> pip install Python/DocumentationUtilsPackage
> pip install Python/DataAugmentationUtilsPackage
> pip install Python/DeepSSMUtilsPackage
> ```

**Comment by iyerkrithika21** [comment]
This is the error after running the use case . I am not sure if this is due to the libff issue or something else. @medakk @jadie1 
```
(shapeworks) iyerkrithika@krithika:~/ShapeWorks/Examples/Python> python RunUseCase.py --use_case deep_ssm --tiny_test
Traceback (most recent call last):
  File "RunUseCase.py", line 57, in <module>
    module = __import__(args.use_case.lower())
  File "/home/sci/iyerkrithika/ShapeWorks/Examples/Python/deep_ssm.py", line 9, in <module>
    import DataAugmentationUtils
  File "/home/sci/iyerkrithika/miniconda3/envs/shapeworks/lib/python3.7/site-packages/DataAugmentationUtils/__init__.py", line 1, in <module>
    from DataAugmentationUtils import DataAugmentation
  File "/home/sci/iyerkrithika/miniconda3/envs/shapeworks/lib/python3.7/site-packages/DataAugmentationUtils/DataAugmentation.py", line 6, in <module>
    from DataAugmentationUtils import Utils
ImportError: cannot import name 'Utils' from 'DataAugmentationUtils' (/home/sci/iyerkrithika/miniconda3/envs/shapeworks/lib/python3.7/site-packages/DataAugmentationUtils/__init__.py)
```

**Comment by iyerkrithika21** [comment]
I am on openSUSE Leap 15.2 with conda 4.9.2
> I'm on Ubuntu 18.04 with conda 4.9.2

**Comment by iyerkrithika21** [comment]
@medakk I merged master to this branch and ran conda_installs and that ran without errors. Also ran conda_installs on master alone and that was fine too.
@jadie1  I am still facing this issue with DataAugmentationUtils.
> 
> 
> This is the error after running the use case . I am not sure if this is due to the libff issue or something else. @medakk @jadie1
> 
> ```
> (shapeworks) iyerkrithika@krithika:~/ShapeWorks/Examples/Python> python RunUseCase.py --use_case deep_ssm --tiny_test
> Traceback (most recent call last):
>   File "RunUseCase.py", line 57, in <module>
>     module = __import__(args.use_case.lower())
>   File "/home/sci/iyerkrithika/ShapeWorks/Examples/Python/deep_ssm.py", line 9, in <module>
>     import DataAugmentationUtils
>   File "/home/sci/iyerkrithika/miniconda3/envs/shapeworks/lib/python3.7/site-packages/DataAugmentationUtils/__init__.py", line 1, in <module>
>     from DataAugmentationUtils import DataAugmentation
>   File "/home/sci/iyerkrithika/miniconda3/envs/shapeworks/lib/python3.7/site-packages/DataAugmentationUtils/DataAugmentation.py", line 6, in <module>
>     from DataAugmentationUtils import Utils
> ImportError: cannot import name 'Utils' from 'DataAugmentationUtils' (/home/sci/iyerkrithika/miniconda3/envs/shapeworks/lib/python3.7/site-packages/DataAugmentationUtils/__init__.py)
> ```

**Comment by medakk** [comment]
I'm not too familiar with this, but it seems like the DataAugmentation stuff should've been installed as part of conda_installs.sh
Did conda_installs fail again?

Try running `pip install Python/DataAugmentationUtilsPackage`

**Comment by iyerkrithika21** [comment]
> 
> 
> I'm not too familiar with this, but it seems like the DataAugmentation stuff should've been installed as part of conda_installs.sh
> Did conda_installs fail again?
> 
> Try running `pip install Python/DataAugmentationUtilsPackage`

After merging master, conda_installs ran successfully. pip install was included in conda_installs.
I am not sure what is causing this error.

**Comment by iyerkrithika21** [comment]
Output of the tiny test
image

**Comment by iyerkrithika21** [comment]
Update: The use case works fine and saves the best and final model. Working with Jadie for fixing a few minor issues with the tiny test run. Since the portal is down, could not download the data required, so Jadie is providing me the tiny test data to run on.

**Review by iyerkrithika21 — APPROVED** [review]

**Comment by jadie1** [comment]
I believe this is ready to merge. If anyone else want's to test it, let me know and I can send you the tiny test data directly since the data portal is still having issues.

**Comment by jadie1** [comment]
@sheryjoe @akenmorris Can this be merged?

**Pull request merged**
