### PR TITLE
Set C++ standard to C++14

### PR DESCRIPTION
**Pull request by akenmorris**
Seeing if ShapeWorks will build with C++17 on all the GitHub action platforms.

### CODE REVIEW

**Comment by cchriste** [comment]
😃

**Comment by akenmorris** [comment]
Well, that seemed to work, but I ran into a very annoying error when trying to actually use it:

error: 'path' is unavailable: introduced in macOS 10.15
  std::filesystem::path path;

Despite the compiler supporting it, you apparently have to run OSX 10.15 to use it :(

**Comment by cchriste** [comment]
Any chance of resolving this? I'm trying to use some stuff that's only available in C++17.

**Comment by akenmorris** [comment]
I can't see any way that doesn't require all Mac developers and users to upgrade to 10.15.  I'm not entirely sure about Windows or Linux.

**Comment by akenmorris** [comment]
Note: as far as I know, only the filesystem module requires 10.15, there could be other C++17 features that work on older Mac OS.  Unfortunately, it seems that you don't find out until you actually try to include and use a particular feature.

**Comment by cchriste** [comment]
I was able to get things working using C++14, so I'll let you decide what to do about upgrading to 17.

**Comment by akenmorris** [comment]
I'd really like to use std::filesystem, but it doesn't even work on my own system, so it's a no-go.

We're currently set to 11, do you want to try 14?

**Comment by cchriste** [comment]
Yes, let's try 14 please.

**Comment by akenmorris** [comment]
Just set CMAKE_CXX_STANDARD to 14 and then use a couple of the features you want (as I found out it's not enough to just set the standard) and let's see if it builds on all the GitHub platforms.  I don't think it will be a problem.  GCC has supported it since 6.1.

**Comment by cchriste** [comment]
I got what I was doing working find with C++11, but I went ahead and
changed it to 14 and pushed so you can try the features that weren't
working for you.

**Comment by akenmorris** [comment]
std::filesystem doesn't exist until C++17.

https://en.cppreference.com/w/cpp/header/filesystem

There are some Qt things in C++14 that are nice.  I've used them on all three platforms before.

**Comment by cchriste** [comment]
I am in favor of moving to at least C++14 then (I actually thought we were
already using it :).

**Pull request merged**
