### PR TITLE
tested successfully with a use case 

### PR DESCRIPTION
**Pull request by prafulag**
ALso updated CMakeLists.txt to move the Find QT to occur only if GUI is on

### CODE REVIEW

**Comment by prafulag** [comment]
@akenmorris : Any idea why QT install failing on windows but passed in Linux ?

**Comment by akenmorris** [comment]
Yes, the install-qt action is broken. I’m trying to deal with it.

**Comment by prafulag** [comment]
okay, thanks

**Comment by akenmorris** [comment]
I've fixed it and merged to master.  If you merge from master and push again it should work now.

**Comment by prafulag** [comment]
@akenmorris: thanks!

**Pull request merged**
