### PR TITLE
Studio updates

### PR DESCRIPTION
**Pull request by akenmorris**
This PR makes the following changes:

* Enable save after save-as from a new/unsaved project
* Fix save-as default location
* Fix "display sample" mode when in analysis
* Fix "export current mesh" (was not working with updated data structures)
* Added PCA raw component score export to Studio (was only in View2 previously)

### CODE REVIEW

**Comment by sheryjoe** [comment]
@jadie1 @AtefehKashani could you test this branch?

**Comment by AtefehKashani** [comment]
@akenmorris  Do I need to rerun the build_dependency before testing?

**Comment by akenmorris** [comment]
I don't know, that depends if you've re-run it since we added OpenVDB and XLNT dependencies.

**Comment by AtefehKashani** [comment]
got it! No I didn't rerun it for awhile, and I have to rerun it.

**Comment by jadie1** [comment]
I tried saving the project as well as the mesh and the pca csv files and it all worked. Let me know if there's anything else I should check

**Comment by AtefehKashani** [comment]
@akenmorris 
I reran the build_dependencies and rebuilt with the new dependencies to test this changes. 
1- When I open the project /Examples/Studio/ellipssoid.xlsx the studio suddenly terminates and does not open the project. I guess there is something wrong with the ellipsoid images, I also couldn't load them with previous versions of the Studio. 
I could load and save projects with other data set, e.g. box bump and LA.
2- when loading an existing analyze.xml the reconstruction is off, does this mean there is no need for reconstruction? 
3- I have tested the PCA component score, sample display and current mesh and all worked.

**Comment by akenmorris** [comment]
@AtefehKashani :

1) I will check on the error handling.  Did the nrrd files not check out from git-lfs properly?  Do you have git-lfs installed?

2) The reconstruction button is disabled?  This will happen if there are no distance transforms provided.

**Comment by AtefehKashani** [comment]
@akenmorris 
1- I have git-lsf installed in the conda environment. How can I test the nrrd files?
2- I have checked this with other examples that I have, which the xml file contains distance transforms, local and world particles The reconstruction is disabled.
Studio_recon

**Comment by akenmorris** [comment]
You can check the nrrd files in several ways.  What do you see when you open them in a text editor like emacs?  Here is the checksum for ellipsoid_1.nrrd

$ md5sum ellipsoid_1.nrrd
f6795103ee573be7dc48c8b2f0d681ae  ellipsoid_1.nrrd

git-lfs needs to be installed and active before you checkout shapeworks, otherwise try:

```
git lfs fetch
git lfs checkout
```

For #2, I'm not sure, I thought this was working.  I will check.  I may need you to point me to some of your data.

**Comment by AtefehKashani** [comment]
@akenmorris 
The git lfs fetch solved the problem with the ellipsoid and I could load the project and run the optimization with studio. 
In this case the "Run Reconstruction" is active and I could run it. But when I load an existing analyze.xml the "Run Reconstruction" isn't active.

**Comment by akenmorris** [comment]
@AtefehKashani , confirmed, that button was incorrectly not enabled in those cases.  Should be fixed now with the latest commits.

**Comment by AtefehKashani** [comment]
@akenmorris I tested the studio with the recent changes and now it is working.

**Pull request merged**
