### PR TITLE
Violin plot in DeepSSM

### PR DESCRIPTION
**Pull request by jadie1**
Adding violin plot to deep_ssm use case instead of splom. 
Tiny test is sufficient for testing.

### CODE REVIEW

**Comment by akenmorris** [comment]
I ran it on windows with --tiny_test, but no charts displayed.  Do they display for --tiny_test mode?

**Comment by akenmorris** [comment]
Screenshot (31)

Great!

**Comment by sheryjoe** [comment]
@jadie1 I wouldn't use underscores in axes labels and legend.

**Review by akenmorris — APPROVED** [review]

**Comment by jadie1** [comment]
I will remove the underscores from the violin plot labels and I will also remove the data_augmentation use case. Everything it does is done in the deep_ssm use case and we have the data augmentation notebook which does a better job of documenting and explaining the process. Then this will be ready to merge!

**Comment by jadie1** [comment]
Here is a plot with updated labels from running the tiny test:
image

Ready to merge now!

**Comment by akenmorris** [comment]
This will be a little complicated to merge now that all of the commits from master were merged in.

**Comment by akenmorris** [comment]
I will make a new branch and cherry pick the commits we want.

**Comment by akenmorris** [comment]
See #1144

**Pull request closed without merging**
