### PR TITLE
Refactor particle domain

### PR DESCRIPTION
**Pull request by akenmorris**
This PR performs a significant refactor of the ParticleDomain hierarchy.  All of these classes are no longer ITK classes and are moved to the shapeworks namespace.

I also cleaned up a lot of old cruft and nonsense templates.

This PR builds on a some other PRs so it may be difficult to look at the diff until they are merged.

### CODE REVIEW

**Review by HeavenlyBerserker — APPROVED** [review]
Looks really good! It was about time. Seems pretty straightforward and mostly cosmetic.

Who all are working on Libs/Optimize? If it's just you and I, can we coordinate to have the itk- prefix removed from half of the filenames in ParticleSystem?

**Comment by akenmorris** [comment]
@iyerkrithika21 , @nawazishkhan1-nk, @jadie1 , does this conflict with anything you are working on?

**Comment by nawazishkhan1-nk** [comment]
> @iyerkrithika21 , @nawazishkhan1-nk, @jadie1 , does this conflict with anything you are working on?

Yes, it does a bit. I have some implementation for multi-level ssm optimizer and I used itk classes for it.

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 , @nawazishkhan1-nk, @jadie1 , does this conflict with anything you are working on?

I think there might be some conflicts. I have made changes to following files in the branch `sub_optimize_python`
- Optimizer.cpp/.h, 
- Sampler.cpp/.h, 
- OptimizeParameterFile.cpp/.h, 
- itkParticleGradientDescentPositionOptimizer.h/.txx

**Comment by akenmorris** [comment]
@iyerkrithika21 , I tried merging this branch with the latest `sub_optimize_python` branch on GitHub and did not run into any conflicts.  The build worked as well.

@nawazishkhan1-nk , if you let push your latest changes to GitHub, I can check your as well.

**Comment by nawazishkhan1-nk** [comment]
> > Yes, it does a bit. I have some implementation for multi-level ssm optimizer and I used itk classes for it.
> 
> It's fine to use ITK classes in general. Have you modified the ParticleDomain hierarchy files in particular?

Nothing specific related to ParticleDomain hierarchy, but there are some files which I added to the ParticleSystem for I will try merging this branch with my work and will let you know if I run into some issues. 

> > Yes, it does a bit. I have some implementation for multi-level ssm optimizer and I used itk classes for it.
> 
> It's fine to use ITK classes in general. Have you modified the ParticleDomain hierarchy files in particular?

Nothing specific related to ParticleDomain hierarchy, but I think there's some file which I added in Optimize/ParticleSystem folder which might get affected by this. I will try merging this branch with my work and will let you know I run into any issues.

**Comment by jadie1** [comment]
> @iyerkrithika21 , @nawazishkhan1-nk, @jadie1 , does this conflict with anything you are working on?

It shouldn't conflict with anything I'm doing.

**Pull request merged**
