### PR TITLE
Fix leak in Mesh::coverage by using smart pointers

### PR DESCRIPTION
**Pull request by akenmorris**

### CODE REVIEW

**Review by cchriste — CHANGES_REQUESTED** [review]
I thought of doing this, but it's likely to crash later on since this function (called by areaCoveraget.Apply where surf1 and surf2 are used) takes ownership of the raw pointer by address:
```c++
void FEAreaCoverage::Surface::Create(FEMesh& mesh)
{
  m_mesh = &mesh;
...
class FEAreaCoverage
{
  class Surface
  {
public:
    FEMesh*       m_mesh;
...
```

**Comment by akenmorris** [comment]
Yeah, these PreviewMeshQC classes need some work, don't they?

**Comment by cchriste** [comment]
Yeah, let's just close this pull request and create an issue so we don't accidentally break something. A memory leak is bad, but freeing an object that may still be in use is worse.

**Comment by akenmorris** [comment]
I've pushed changes that replace all the pointers and references with shared pointers.

There is no critical need to merge this immediately.  The only code using this is to run it from the command line which a user will only do once per process timeline.

**Comment by cchriste** [comment]
Cool. After a quick perusal, I feel this update is solid. Just to be extra safe let's wait till after the release to merge it.

**Comment by cchriste** [comment]
We've enough work left on this release (e.g., add the remaining Mesh API to Python) that this change will still have plenty of time to be tested. Plus it looks safer than what we have. Merging. (the failed test was fixed awhile ago in the main branch)

**Pull request merged**
