### PR TITLE
Install Miniconda in non-interactive mode

### PR DESCRIPTION
**Pull request by danlamanna**
This should be in line with the rest of the script using the analogous `--yes` flags.

https://docs.anaconda.com/anaconda/install/silent-mode/#linux-macos

### CODE REVIEW

**Comment by danlamanna** [comment]
It looks like this was working in Linux/Mac CI previously because Miniconda is installed before `conda_installs.sh` is run.

**Comment by akenmorris** [comment]
Seems good to me,  @cchriste ?

**Comment by cchriste** [comment]
> Seems good to me, @cchriste ?

Looks good except for the failed GitHub actions. I just restarted them since they don't make sense (Linux was a permissions issue from GitHub and Windows was the one-minute-wonder fail).

**Comment by cchriste** [comment]
Looks like the Windows action is failing and I don't see why. `aqt` conda install?

**Comment by akenmorris** [comment]
I don't think master has the most recent aqt updates, only in the release branch.

For the permission, is that because it's coming from Dan and not one of us?

**Comment by cchriste** [comment]
> I don't think master has the most recent aqt updates, only in the release branch.

So every pull request to master is now broken?

> For the permission, is that because it's coming from Dan and not one of us?

Does this mean every time the GitHub action run, even for only a pull request, it uploads the updated docs to `gh-pages`?
```
INFO    -  Copying '/home/runner/work/ShapeWorks/ShapeWorks/site' to 'gh-pages' branch and pushing to GitHub. 
1230
ERROR   -  Failed to deploy to GitHub with error: 
1231
remote: Permission to SCIInstitute/ShapeWorks.git denied to github-actions[bot].
1232
fatal: unable to access 'https://github.com/SCIInstitute/ShapeWorks.git/': The requested URL returned error: 403
```

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
