### PR TITLE
Address #1417 - Add scalar value export option for particles

### PR DESCRIPTION
**Pull request by akenmorris**
Addresses:

* #1417 

image

Example output:

image

This also enhances the mesh scalar output to support multi-component scalars.

### CODE REVIEW

**Comment by patkins** [comment]
I haven’t tried this yet, but my first thought is whether the user has to do this for each shape or if this generates a file for each shape? It may be helpful to also have the current mesh option to export values for group means or PCA modes.

**Comment by akenmorris** [comment]
At the moment, it's just the currently displayed shape.  We have an option to export particles along PCA modes and we could extend the scalar display to do that as well.

For group means, at the moment, you'd have to view each group mean and export them.  Do you want a menu option that is "Export Group Mean Particle Scalars" ?

**Comment by akenmorris** [comment]
Do you want this feature as well, export a table of particles by shapes?  Only one scalar?

**Comment by patkins** [comment]
A single export for all input shapes would be very useful for some of our projects, but the format of the export (whether there is a file per feature value with all shapes or a file per shape with all features) does not matter. I think the format you showed above would work well for the file per shape option too and then it would be consistent across the board.

**Comment by akenmorris** [comment]
@patkins , I've added another export for all subjects, all scalars:

image

This will write a file for every subject as you described.

**Comment by akenmorris** [comment]
@patkins , you can find builds here if you want to try the export:

http://www.sci.utah.edu/~amorris/1752/

**Pull request merged**
