### PR TITLE
Generate shape

### PR DESCRIPTION
**Pull request by iyerkrithika21**
This pull request is for the shape generator python package. It generates ellipsoids and supershapes(meshes, segmentations, and images) dataset.
It can be tested using the tutorial notebook added in the Examples/Python/notebook/tutorials folder.
This should be merged only after pybind merge #798 is complete

### CODE REVIEW

**Comment by sheryjoe** [comment]
@iyerkrithika21 you could have this PR merge to pybind rather than master.

**Comment by sheryjoe** [comment]
I plan to test this PR too. Stay tuned :)

**Comment by HeavenlyBerserker** [comment]
Does anybody else get errors on the unit tests? @archanasri @sheryjoe It seems OptimizeTests.embedded_python_test is failing for no reason. I'm getting the following

> Reading inputfile: sphere_DT.nrrd...
> Reading inputfile: sphere_DT.nrrd...
> Running Python File: python_embedded.py
> unknown file: Failure
> C++ exception with description "make_tuple(): unable to convert argument of type 'shapeworks::Optimize*' to Python object" thrown in the test body.
> [  FAILED  ] OptimizeTests.embedded_python_test (9245 ms)
> [----------] 6 tests from OptimizeTests (208295 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 6 tests from 1 test suite ran. (208295 ms total)
> [  PASSED  ] 5 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] OptimizeTests.embedded_python_test
> 
>  1 FAILED TEST

**Comment by HeavenlyBerserker** [comment]
@jadie1 Can you run Examples/Python/notebook/tutorials/getting-started-with-ShapeGenerator.ipynb and see if you get the following traceback on the line `segFiles = ellipsoid_generator.generate_segmentations()`?

> 
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-16-0245c4571757> in <module>
> ----> 1 segFiles = ellipsoid_generator.generate_segmentations()
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/site-packages/ShapeCohortGen/CohortGenerator.py in generate_segmentations(self, randomize_size, spacing, allow_on_boundary)
>      11                         print("Error: No meshes have been generated to get segmentations from.\n Call 'generate' first.")
>      12                         return
> ---> 13                 self.segs = CohortGenUtils.generate_segmentations(self.meshes, self.out_dir, randomize_size, spacing, allow_on_boundary)
>      14                 return self.segs
>      15         def generate_images(self):
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/site-packages/ShapeCohortGen/CohortGenUtils.py in generate_segmentations(meshList, out_dir, randomize_size, spacing, allow_on_boundary)
>     137         VTKMeshList = get_file_with_ext(meshList,'vtk')
>     138         #get the origin and size based on all the meshes in the VTKMeshList
> --> 139         origin, size = getMeshInfo(meshDir, VTKMeshList, spacing)
>     140         all_mesh_data = {}
>     141         all_mesh_data["origin"] = origin
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/site-packages/ShapeCohortGen/CohortGenUtils.py in getMeshInfo(outDir, meshList, spacing)
>     118         # Get origin and size
>     119         execCommand = ["ComputeRasterizationVolumeOriginAndSize", xmlfilename]
> --> 120         subprocess.check_call(execCommand)
>     121         os.remove(xmlfilename)
>     122         origin_file = open(out_origin, 'r')
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
>     356     check_call(["ls", "-l"])
>     357     """
> --> 358     retcode = call(*popenargs, **kwargs)
>     359     if retcode:
>     360         cmd = kwargs.get("args")
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/subprocess.py in call(timeout, *popenargs, **kwargs)
>     337     retcode = call(["ls", "-l"])
>     338     """
> --> 339     with Popen(*popenargs, **kwargs) as p:
>     340         try:
>     341             return p.wait(timeout=timeout)
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
>     798                                 c2pread, c2pwrite,
>     799                                 errread, errwrite,
> --> 800                                 restore_signals, start_new_session)
>     801         except:
>     802             # Cleanup if the child failed starting.
> 
> ~/anaconda3/envs/shapeworks/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
>    1549                         if errno_num == errno.ENOENT:
>    1550                             err_msg += ': ' + repr(err_filename)
> -> 1551                     raise child_exception_type(errno_num, err_msg, err_filename)
>    1552                 raise child_exception_type(err_msg)
>    1553 
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'ComputeRasterizationVolumeOriginAndSize': 'ComputeRasterizationVolumeOriginAndSize'

**Comment by jadie1** [comment]
@HeavenlyBerserker I'm not seeing that. Can you try calling `ComputeRasterizationVolumeOriginAndSize` from the command line to make sure it built properly?

**Comment by HeavenlyBerserker** [comment]
Update: I've created a new build directory to see if it was a problem with the previous build I have. Will report on the results.

**Comment by iyerkrithika21** [comment]
> 
> 
> Update: I've created a new build directory to see if it was a problem with the previous build I have. Will report on the results.

@HeavenlyBerserker the Linux build is failing right now after I merged master.
#874 should fix this issue.

**Comment by HeavenlyBerserker** [comment]
Update: I tried the notebook on this branch before the merge from master with my new build. It still gives me the same error. Let me try on the one after the fix.

**Comment by iyerkrithika21** [comment]
@HeavenlyBerserker can you also try to run the `ComputeRasterizationVolumeOriginAndSize` (from the command line) on the 'master' branch and the `generate_shape` branch?

**Comment by HeavenlyBerserker** [comment]
What input should I use?

**Comment by jadie1** [comment]
> What input should I use?
The error you were seeing was "No such file or directory: 'ComputeRasterizationVolumeOriginAndSize'" right? So just try calling `ComputeRasterizationVolumeOriginAndSize` from the command line to see if it finds the command. If it does the notebook should work.

I cleaned up the notebook to better match the others like getting-started-with-grooming-segmentations.ipynb.

**Comment by HeavenlyBerserker** [comment]
I see. It worked. I just had to restart the terminal to let .bashrc run. Thanks y'all. The functionality looks solid. Good job!

I have a few stylistic comments that do not need to be addressed. I'll leave it at your discretion which to address.
- The conversion functions are good since they showcase what it is being done, but the visualization functions can maybe be imported from a python script, and just say look at said script if you're curious.
- Scrolling through the notebook is very slow when just running all due to the heavy visualizations. Maybe have the visualizations automatically disappear somehow unless explicitly told to remain.
- As a user presented with this tool for the first time, a more thorough introduction to the capabilities of this tool early on might be helpful. In particular, in section 1.2, maybe talk about what a shape cohort is and what kind of shape cohorts can be generated (e.g. collections of ellipsoids with different parameters) and why you'd like to do this (e.g. test certain functionalities in shapeworks, familiarize yourself with the optimization tools). Also, maybe say mention that files will be generated that can run on shapeworks (I'm assuming vtk files), and which could be good output directories for it to readily be ran with shapeworks.
- Along a similar vein, showing a few pngs of examples of cohorts in 1.2 will give the user a very clear understanding of what this tool is capable of. It will also give an idea of what a supershape is.
- For visualizations, maybe give a caption of what we are looking at; e.g. the following visualization shows the cohort of ellipsoids generated, each with different parameters.

**Review by HeavenlyBerserker — APPROVED** [review]

**Comment by archanasri** [comment]
The kernel keeps dying. Did anyone else face this issue?

**Comment by iyerkrithika21** [comment]
> 
> 
> The kernel keeps dying. Did anyone else face this issue?

@archanasri, can you share where your kernel crashes? As a check, can you try running other tutorial notebooks to see if this problem occurs just for this notebook or others as well?
@jadie1 @HeavenlyBerserker and I did not face this issue.

**Comment by jadie1** [comment]
@sheryjoe this notebook is ready for your review. When you think it is good to go I will add the videos of the output for the documentation.

**Review by sheryjoe — APPROVED** [review]

**Comment by sheryjoe** [comment]
@jadie1 I commited my changes. please review and merge.

**Comment by jadie1** [comment]
I added the videos and documentation. This is ready to merge!

**Review by archanasri — APPROVED** [review]

**Pull request merged**
