### PR TITLE
DeepSSMViz

### PR DESCRIPTION
**Pull request by jadie1**
Note: I branched DeepSSMViz off of the DeepSSM branch, so PR #817 should be merged before this. 

This pull request addresses two issues:
-  Issue #737 Adding parallel violin plots for data augmentation visualization. 
- Issue #624 Adding a notebook to demonstrate the data augmentation process and visualization. This shows the effect of using different sampling distributions. 

To test, run `getting-started-with-data-augmentation.ipynb` which is at /ShapeWorks/Examples/Python/notebooks/tutorials/ 
Note that this notebook links to documentation on the master branch, but the documentation on the mkdocs branch is more up to date.

### CODE REVIEW

**Comment by medakk** [comment]
1. The notebook works for me, all three data augmentation methods + the violin plots displayed. An aside, it would be cool to display a couple of the generated augmented images in addition to the plots. 
2. Avoid the usage of the term "fabricated" in [the doc first paragraph](http://sciinstitute.github.io/ShapeWorks/deep-learning/data-augmentation.html); sounds deceitful.
3. (perhaps unrelated to this PR) This  pattern is not useful IMO:
```python
# let's import shapeworks library to test whether shapeworks is now set
try:
    import shapeworks as sw
except ImportError:
    print('ERROR: shapeworks library failed to import')
else:
    print('SUCCESS: shapeworks library is successfully imported!!!')
```
when it fails, I have no clue why its failing because the error message is discarded. `import shapeworks as sw` should suffice.

**Comment by jadie1** [comment]
@medakk Thanks for reviewing! I added some of those changes and added this notebook to the documentation. I think it is ready to merge.

**Comment by HeavenlyBerserker** [comment]
I can't download the femur-v0 dataset. It gets stuck at 531 MB. Is the server just misbehaving temporarily?

Screenshot from 2021-01-19 09-51-10

**Comment by sheryjoe** [comment]
@HeavenlyBerserker @medakk where are we one reviewing and testing this PR?

**Comment by medakk** [comment]
I think it's good to go.

@HeavenlyBerserker something's wrong with that dataset. I can upload it to some shared SCI folder if you want

**Review by medakk — APPROVED** [review]

**Comment by HeavenlyBerserker** [comment]
@medakk Please do. I just need that dataset to test it. Thanks.

**Review by HeavenlyBerserker — APPROVED** [review]

**Comment by jadie1** [comment]
@sheryjoe Can we merge this?

**Review by sheryjoe — APPROVED** [review]

**Pull request merged**
