### PR TITLE
Studio DeepSSM

### PR DESCRIPTION
**Pull request by akenmorris**
This PR implements phase one of #977 and includes:

- [x] #1371
- [x] #1372
- [x] #1373
- [x] #1374

Phase one includes the same assumptions that the current deep_ssm use cases contains.  Namely that the images are already pre-groomed.

image

image

image

image

### CODE REVIEW

**Comment by jadie1** [comment]
I am seeing an issue where if I change the number of dims in augmentation, it is not relayed to the training part and it throws an error. For example, if I change "Number of PCA Dimensions" to 6 in augmentation, then when I run training I get the error: 

> "Error: RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1 At: /home/sci/jadie/software/anaconda3/envs/shapeworks/lib/python3.7/site-packages/DeepSSMUtils/trainer.py(104): supervised_train /home/sci/jadie/software/anaconda3/envs/shapeworks/lib/python3.7/site-packages/DeepSSMUtils/trainer.py(52): train /home/sci/jadie/software/anaconda3/envs/shapeworks/lib/python3.7/site-packages/DeepSSMUtils/__init__.py(25): trainDeepSSM "

Because it is expecting there to only be 3 PCA dims but there are 6.

**Comment by akenmorris** [comment]
> number of dims

Ok, let me check on it.  I don't think the auto-dims part got implemented either now that I think of it.

**Comment by akenmorris** [comment]
@jadie1 , the number of dimensions stuff should all be fixed now in the latest commit.

**Comment by jadie1** [comment]
Looks like the number of dimensions is working as expected now!

I did notice one other thing, after running training if you resize the viewer the heat map goes away (see screenshots)

Before resizing:
image
After resizing: 
image

**Comment by akenmorris** [comment]
Hmm, I haven't been able to reproduce that.  When I change the number of viewers, the error heat map stays.

Yeah, we could force to 2x2.

**Comment by akenmorris** [comment]
I think the colormap issue is a problem with the scalar ranges not being reset.  In your second image, the scale goes to 20,000.

Let me investigate and fix.

**Review by jadie1 — APPROVED** [review]
Tested on multiple datasets and it looks like everything is working as expected now!

**Pull request merged**
