### PR TITLE
API Consolidation: Images

### PR DESCRIPTION
**Pull request by archanasri**

### CODE REVIEW

**Comment by cchriste** [comment]
I know you're all on the edges of your seats for this one, and just wanted to let you know it's close to ready. The open pull request helps by automatically building everywhere when changes are made. We'll let you know when it's ready to be merged. Thanks for your patience.

**Comment by akenmorris** [comment]
I ran the femur use case and got:

CMD: shapeworks read-image --name TestFemur/femur/images/m09_1x_hip.nrrd reflect --x -1 --y 1 --z 1 write-image --name TestFemur/PrepOutput/reflected/images/m09_R_1x_hip.reflect.nrrd
Usage: reflect [args]...

reflect: error: no such option: --x
General exception caught.
        Returncode: 2
        Output: None

**Comment by sheryjoe** [comment]
Got the below error when running the full ellispoid example:

Step 4. Optimize - Particle Based Optimization

Starting Factor 5
./TestEllipsoids/PointFiles/correspondence_32.xml
General exception caught.
	Returncode: 1
	Output: None

itk::ExceptionObject (0x7fea7b11a680)
Location: "unknown" 
File: /path/to/shapeworks/Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
Line: 162
Description: itk::ERROR: DataObject(0x7fea7b317cb0): Distance transform queried for a Point, [-34.9141, 0.471236, -11.6449], outside the given image domain. Consider increasing the narrow band

**Comment by sheryjoe** [comment]
Got the below error when running the full left atrium with images. Was this error fixed in a different branch? Was this branch merged to master?

Traceback (most recent call last):
  File "RunUseCase.py", line 66, in <module>
    module.Run_Pipeline(args)
  File "/path/to/shapeworks/Examples/Python/left_atrium.py", line 169, in Run_Pipeline
    [croppedFiles_segmentations, croppedFiles_images] = applyCropping(parentDir, rigidFiles_segmentations,  rigidFiles_images, processRaw=True)
TypeError: applyCropping() got an unexpected keyword argument 'processRaw'

**Comment by archanasri** [comment]
> Got the below error when running the full left atrium with images. Was this error fixed in a different branch? Was this branch merged to master?
> 
> Traceback (most recent call last):
> File "RunUseCase.py", line 66, in
> module.Run_Pipeline(args)
> File "/path/to/shapeworks/Examples/Python/left_atrium.py", line 169, in Run_Pipeline
> [croppedFiles_segmentations, croppedFiles_images] = applyCropping(parentDir, rigidFiles_segmentations, rigidFiles_images, processRaw=True)
> TypeError: applyCropping() got an unexpected keyword argument 'processRaw'

We had made changes for this error to not occur. A merge from the master could have caused this. I have fixed it now. Will push the changes.

**Comment by archanasri** [comment]
> I ran the femur use case and got:
> 
> CMD: shapeworks read-image --name TestFemur/femur/images/m09_1x_hip.nrrd reflect --x -1 --y 1 --z 1 write-image --name TestFemur/PrepOutput/reflected/images/m09_R_1x_hip.reflect.nrrd
> Usage: reflect [args]...
> 
> reflect: error: no such option: --x
> General exception caught.
> Returncode: 2
> Output: None

Fixed with the latest commit

**Comment by cchriste** [comment]
> Got the below error when running the full left atrium with images. Was this error fixed in a different branch? Was this branch merged to master?
> 
> Traceback (most recent call last):
> File "RunUseCase.py", line 66, in 
> module.Run_Pipeline(args)
> File "/path/to/shapeworks/Examples/Python/left_atrium.py", line 169, in Run_Pipeline
> [croppedFiles_segmentations, croppedFiles_images] = applyCropping(parentDir, rigidFiles_segmentations, rigidFiles_images, processRaw=True)
> TypeError: applyCropping() got an unexpected keyword argument 'processRaw'

I'm glad we have tests that break, but I'm not sure how to fix this one. The issue is that ITK's definition of the center of the image is considered to be the physical point between the centers of the first and last pixels/voxels (like the image in this message: https://itk.org/pipermail/insight-users/2008-January/024771.html). This is why recenter results in an "odd" origin (ex: the 50^3 ellipsoid's center becomes -24.5^3). 

We manually compute the center using the full image, but we let ITK use its own definition for the recenter function. I'm going to try changing that and see how far we get with it.

**Comment by cchriste** [comment]
> > Got the below error when running the full left atrium with images. Was this error fixed in a different branch? Was this branch merged to master?
> > Traceback (most recent call last):
> > File "RunUseCase.py", line 66, in
> > module.Run_Pipeline(args)
> > File "/path/to/shapeworks/Examples/Python/left_atrium.py", line 169, in Run_Pipeline
> > [croppedFiles_segmentations, croppedFiles_images] = applyCropping(parentDir, rigidFiles_segmentations, rigidFiles_images, processRaw=True)
> > TypeError: applyCropping() got an unexpected keyword argument 'processRaw'
> 
> I'm glad we have tests that break, but I'm not sure how to fix this one. The issue is that ITK's definition of the center of the image is considered to be the physical point between the centers of the first and last pixels/voxels (like the image in this message: https://itk.org/pipermail/insight-users/2008-January/024771.html). This is why recenter results in an "odd" origin (ex: the 50^3 ellipsoid's center becomes -24.5^3).
> 
> We manually compute the center using the full image, but we let ITK use its own definition for the recenter function. I'm going to try changing that and see how far we get with it.

Well, it actually seems very appropriate to change the recenter to behave like everything else seems to, but it doesn't fix this particular problem. I think it's an issue with the optimize code but I'm not sure why it only appeared here. We'll need help investigating, so its author should join this conversation.

**Comment by sheryjoe** [comment]
> > > Got the below error when running the full left atrium with images. Was this error fixed in a different branch? Was this branch merged to master?
> > > Traceback (most recent call last):
> > > File "RunUseCase.py", line 66, in
> > > module.Run_Pipeline(args)
> > > File "/path/to/shapeworks/Examples/Python/left_atrium.py", line 169, in Run_Pipeline
> > > [croppedFiles_segmentations, croppedFiles_images] = applyCropping(parentDir, rigidFiles_segmentations, rigidFiles_images, processRaw=True)
> > > TypeError: applyCropping() got an unexpected keyword argument 'processRaw'
> > 
> > 
> > I'm glad we have tests that break, but I'm not sure how to fix this one. The issue is that ITK's definition of the center of the image is considered to be the physical point between the centers of the first and last pixels/voxels (like the image in this message: https://itk.org/pipermail/insight-users/2008-January/024771.html). This is why recenter results in an "odd" origin (ex: the 50^3 ellipsoid's center becomes -24.5^3).
> > We manually compute the center using the full image, but we let ITK use its own definition for the recenter function. I'm going to try changing that and see how far we get with it.
> 
> Well, it actually seems very appropriate to change the recenter to behave like everything else seems to, but it doesn't fix this particular problem. I think it's an issue with the optimize code but I'm not sure why it only appeared here. We'll need help investigating, so its author should join this conversation.

Why is this error related to centering?

**Comment by cchriste** [comment]
Like I said, changing recenter did not fix the error. I don’t know what the
error relates to and we need some help figuring it out.

**Comment by sheryjoe** [comment]
> Like I said, changing recenter did not fix the error. I don’t know what the error relates to and we need some help figuring it out.
> […](#)

The error is about an input argument for applyCropping() function. 
**TypeError: applyCropping() got an unexpected keyword argument 'processRaw'**

Anyways, I am not seeing this anymore in the repo. May be @archanasri has fixed this already. I will rerun the LA use case.

**Comment by sheryjoe** [comment]
@archanasri @akenmorris With the lastest pull from the exec branch. I am still getting the below error for the ellispoid use case.

itk::ExceptionObject (0x7ff78ac5a3d0)
Location: "unknown" 
File: .../Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
Line: 162
Description: itk::ERROR: DataObject(0x7ff78af98220): Distance transform queried for a Point, [-35.4141, -0.0287641, -12.1449], outside the given image domain. Consider increasing the narrow band

**Comment by akenmorris** [comment]
It seems like something is wrong with the grooming.  Have you looked at the resulting distance transforms passed to ShapeWorksRun?

executable_ellipsoid

These don't seem centered, and one is going off the image.  This is why it is complaining that a point at X=-35.4141 is outside the narrow band.  The image is ending in -35.0.

Compare to what we had before:

master_ellipsoid

**Comment by cchriste** [comment]
> It seems like something is wrong with the grooming. Have you looked at the resulting distance transforms passed to ShapeWorksRun?
> 
> executable_ellipsoid
> 
> These don't seem centered, and one is going off the image. This is why it is complaining that a point at X=-35.4141 is outside the narrow band. The image is ending in -35.0.
> 
> Compare to what we had before:
> 
> master_ellipsoid

I agree, and that's exactly what I'm doing right now. Thanks, Alan.

**Comment by cchriste** [comment]
> > It seems like something is wrong with the grooming. Have you looked at the resulting distance transforms passed to ShapeWorksRun?
> 
> I agree, and that's exactly what I'm doing right now. Thanks, Alan.

The problem is the com alignment. We'll figure it out. Thanks for your help everyone.

**Comment by archanasri** [comment]
> > Like I said, changing recenter did not fix the error. I don’t know what the error relates to and we need some help figuring it out.
> > […](#)
> 
> The error is about an input argument for applyCropping() function.
> **TypeError: applyCropping() got an unexpected keyword argument 'processRaw'**
> 
> Anyways, I am not seeing this anymore in the repo. May be @archanasri has fixed this already. I will rerun the LA use case.

Yeah, this has been fixed.

**Comment by sheryjoe** [comment]
Another error for la use case:

Usage: bounding-box [args]...

bounding-box: error: --names option requires an argument

**Comment by cchriste** [comment]
> > > It seems like something is wrong with the grooming. Have you looked at the resulting distance transforms passed to ShapeWorksRun?
> > 
> > 
> > I agree, and that's exactly what I'm doing right now. Thanks, Alan.
> 
> The problem is the com alignment. We'll figure it out. Thanks for your help everyone.

It was something simple in the GroomUtils script. We create a handy function to get the info (center, com, origin, etc) and return a point. When we used this function we just had the arguments for the com translation backwards (com - center instead of center - com). Committed and running GitHub action tests (we also added a few more iterations to the ellipsoid tiny_test to be more thorough, but maybe we should just do the whole thing?). We're also running the femur use case again to ensure it works.

**Comment by sheryjoe** [comment]
Running LA on the lastest pull of exec branch produced the following error.

Traceback (most recent call last):
  File "RunUseCase.py", line 70, in <module>
    module.Run_Pipeline(args)
  File ".../Examples/Python/left_atrium.py", line 141, in Run_Pipeline
    [comFiles_segmentations, comFiles_images] = applyCOMAlignment(parentDir + "com_aligned", paddedFiles_segmentations, raw=paddedFiles_images)
TypeError: applyCOMAlignment() got an unexpected keyword argument 'raw'

**Comment by archanasri** [comment]
> Got the below error when running the full ellispoid example:
> 
> Step 4. Optimize - Particle Based Optimization
> 
> Starting Factor 5
> ./TestEllipsoids/PointFiles/correspondence_32.xml
> General exception caught.
> Returncode: 1
> Output: None
> 
> itk::ExceptionObject (0x7fea7b11a680)
> Location: "unknown"
> File: /path/to/shapeworks/Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
> Line: 162
> Description: itk::ERROR: DataObject(0x7fea7b317cb0): Distance transform queried for a Point, [-34.9141, 0.471236, -11.6449], outside the given image domain. Consider increasing the narrow band

Fixed.

**Comment by archanasri** [comment]
> @archanasri @akenmorris With the lastest pull from the exec branch. I am still getting the below error for the ellispoid use case.
> 
> itk::ExceptionObject (0x7ff78ac5a3d0)
> Location: "unknown"
> File: .../Libs/Optimize/ParticleSystem/itkParticleImageDomain.h
> Line: 162
> Description: itk::ERROR: DataObject(0x7ff78af98220): Distance transform queried for a Point, [-35.4141, -0.0287641, -12.1449], outside the given image domain. Consider increasing the narrow band

Fixed.

**Comment by archanasri** [comment]
> Another error for la use case:
> 
> Usage: bounding-box [args]...
> 
> bounding-box: error: --names option requires an argument

Fixed.

**Comment by archanasri** [comment]
> Running LA on the lastest pull of exec branch produced the following error.
> 
> Traceback (most recent call last):
> File "RunUseCase.py", line 70, in
> module.Run_Pipeline(args)
> File ".../Examples/Python/left_atrium.py", line 141, in Run_Pipeline
> [comFiles_segmentations, comFiles_images] = applyCOMAlignment(parentDir + "com_aligned", paddedFiles_segmentations, raw=paddedFiles_images)
> TypeError: applyCOMAlignment() got an unexpected keyword argument 'raw'

Fixed.

**Comment by sheryjoe** [comment]
Running ellispoid (on mac) did not launch ShapeWorksStudio although ShapeWorks/build/bin is in the path. 

Also, I can't run ShapeWorksStudio from the terminal unless I run it from its path like this: .../build/bin/ShapeWorksStudio.app/Contents/MacOS/ShapeWorksStudio 

Any thoughts?

Traceback (most recent call last):
  File "RunUseCase.py", line 70, in <module>
    module.Run_Pipeline(args)
  File ".../Examples/Python/ellipsoid.py", line 234, in Run_Pipeline
    launchShapeWorksStudio(pointDir, dtFiles, localPointFiles, worldPointFiles)
  File ".../Examples/Python/AnalyzeUtils.py", line 54, in launchShapeWorksStudio
    subprocess.check_call(execCommand )
  File ".../anaconda3/envs/shapeworks/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File ".../anaconda3/envs/shapeworks/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File ".../anaconda3/envs/shapeworks/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File ".../anaconda3/envs/shapeworks/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ShapeWorksStudio': 'ShapeWorksStudio'

**Comment by sheryjoe** [comment]
Ellispoid use case does produce a good model.

Variability is leaking beyond the first mode.
image

And not good sampling.
image

**Comment by cchriste** [comment]
For the use case, that can be fixed. I’ll do it now, and it will work for
everyone with the ShapeWorks bin directory in their path, not just people
who happen to use ../../build/bin.

For studio I’m guessing this has always been the case. Welcome to OSX.
Maybe we can add a shell script to bin. Or it might work if you use “open
ShapeWorksStudio” (not sure if open searches your path).

**Comment by cchriste** [comment]
> For the use case, that can be fixed. I’ll do it now, and it will work for everyone with the ShapeWorks bin directory in their path, not just people who happen to use ../../build/bin. For studio I’m guessing this has always been the case. Welcome to OSX. Maybe we can add a shell script to bin. Or it might work if you use “open ShapeWorksStudio” (not sure if open searches your path).
> […](#)

The first item is now fixed and for the second I created issue #615.

**Comment by cchriste** [comment]
> Ellispoid use case does produce a good model.
Do you mean "does not?"

> **Variability is leaking beyond the first mode.**
> 
> The second mode captures translation indicating an issue in the alignment step of the groom. See attached.
> 
> And not good sampling.

I've run the full ellipsoid use case on both builds and can see the difference (how do I adjust the particle size like your picture shows?). In the intermediate outputs. In the [com_]aligned images' origin/center are different like we discussed in Tuesday's meeting. This results in slightly different bounding boxes and centers of mass as well. Note that the original segmentations use the "full image" physical coordinates like our updated methods.

If alignment is the issue, can we identify any deprecated components that are still being used? It may be these assume the pixel-center bounds rather than the full image bounds. Next, would the provided meshes result in some sort of hard-coded expectation for the images used for particle distribution? 

*orig:*
```
$ shapeworks readimage --name original.nrrd info
image dimensions:      [50, 50, 50]
physical spacing:      [1, 1, 1]
size (spacing * dims): [50, 50, 50]
physical origin:       [0, 0, 0]
center:                [25, 25, 25]
center of mass (0,1]:  [25, 25, 25]
```

*master:*
```
$ shapeworks readimage --name aligned.nrrd info
image dimensions:      [70, 70, 70]
physical spacing:      [1, 1, 1]
size (spacing * dims): [70, 70, 70]
physical origin:       [-34.5, -34.5, -34.5]
center:                [0.5, 0.5, 0.5]
center of mass (0,1]:  [-0.0346221, -0.0556964, -0.0336714]
bounding box:          {
	min: [17, 26, 26],
	max: [52, 43, 43]
}
```

*executable:*
```
$ shapeworks readimage --name aligned.nrrd info
image dimensions:      [70, 70, 70]
physical spacing:      [1, 1, 1]
size (spacing * dims): [70, 70, 70]
physical origin:       [-35, -35, -35]
center:                [0, 0, 0]
center of mass (0,1]:  [-0.252622, -0.124118, -0.199809]
bounding box:          {
	min: [18, 27, 27],
	max: [52, 43, 43]
}
```

*comparison:*
```
$ shapeworks readimage --name executable.aligned.nrrd compare --name master.aligned.nrrd
Comparison failed: itk::ERROR: ComparisonImageFilter(0x7fda31160140): Inputs do not occupy the same physical space! 
InputImage Origin: [-3.5000000e+01, -3.5000000e+01, -3.5000000e+01], InputImageValidInput Origin: [-3.4500000e+01, -3.4500000e+01, -3.4500000e+01]
	Tolerance: 1.0000000e-06

1066 pixels differ
compare failure
```

**Comment by cchriste** [comment]
> > Ellispoid use case does produce a good model.
> > Do you mean "does not?"
> 
> > **Variability is leaking beyond the first mode.**
> > The second mode captures translation indicating an issue in the alignment step of the groom. See attached.
> > And not good sampling.
> 
> _I'm working on it. The images in com_aligned are different (note the pixel counts at the end), not just in slightly different locations. We had this fixed yesterday, so not sure what might have come up again._
> 
> I've run the full ellipsoid use case on both builds and can see the difference (how do I adjust the particle size like your picture shows?). In the intermediate outputs. In the [com_]aligned images' origin/center are different like we discussed in Tuesday's meeting. This results in slightly different bounding boxes and centers of mass as well. Note that the original segmentations use the "full image" physical coordinates like our updated methods.
> 
> If alignment is the issue, can we identify any deprecated components that are still being used? It may be these assume the pixel-center bounds rather than the full image bounds. Next, would the provided meshes result in some sort of hard-coded expectation for the images used for particle distribution?
> 
> _orig:_
> 
> ```
> $ shapeworks readimage --name original.nrrd info
> image dimensions:      [50, 50, 50]
> physical spacing:      [1, 1, 1]
> size (spacing * dims): [50, 50, 50]
> physical origin:       [0, 0, 0]
> center:                [25, 25, 25]
> center of mass (0,1]:  [25, 25, 25]
> ```
> 
> _master:_
> 
> ```
> $ shapeworks readimage --name aligned.nrrd info
> image dimensions:      [70, 70, 70]
> physical spacing:      [1, 1, 1]
> size (spacing * dims): [70, 70, 70]
> physical origin:       [-34.5, -34.5, -34.5]
> center:                [0.5, 0.5, 0.5]
> center of mass (0,1]:  [-0.0346221, -0.0556964, -0.0336714]
> bounding box:          {
> 	min: [17, 26, 26],
> 	max: [52, 43, 43]
> }
> ```
> 
> _executable:_
> 
> ```
> $ shapeworks readimage --name aligned.nrrd info
> image dimensions:      [70, 70, 70]
> physical spacing:      [1, 1, 1]
> size (spacing * dims): [70, 70, 70]
> physical origin:       [-35, -35, -35]
> center:                [0, 0, 0]
> center of mass (0,1]:  [-0.252622, -0.124118, -0.199809]
> bounding box:          {
> 	min: [18, 27, 27],
> 	max: [52, 43, 43]
> }
> ```
> 
> _comparison:_
> 
> ```
> $ shapeworks readimage --name executable.aligned.nrrd compare --name master.aligned.nrrd
> Comparison failed: itk::ERROR: ComparisonImageFilter(0x7fda31160140): Inputs do not occupy the same physical space! 
> InputImage Origin: [-3.5000000e+01, -3.5000000e+01, -3.5000000e+01], InputImageValidInput Origin: [-3.4500000e+01, -3.4500000e+01, -3.4500000e+01]
> 	Tolerance: 1.0000000e-06
> 
> 1066 pixels differ
> compare failure
> ```

@sheryjoe 

The code below, from TranslateShapeToImageOrigin.cxx in Libs/Alignment from master branch, incorrectly computes the center of the image:
```
    // get the center of the image region (bounding box), translate the object's center to this center so that the shape will be at the center of the image
    InputImageType::PointType origin = inputImage->GetOrigin();
    InputImageType::SizeType   size  = inputImage->GetLargestPossibleRegion().GetSize();

    InputImageType::IndexType index;
    InputImageType::PointType point;
    InputImageType::PointType center;

    index[0] = 0; index[1] = 0; index[2] = 0;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] = point[0]; center[1] = point[1]; center[2] = point[2];

    index[0] = 0; index[1] = 0; index[2] = size[2]-1;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    index[0] = 0; index[1] = size[1]-1; index[2] = 0;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    index[0] = 0; index[1] = size[1]-1; index[2] = size[2]-1;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    index[0] = size[0]-1; index[1] = 0; index[2] = 0;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    index[0] = size[0]-1; index[1] = 0; index[2] = size[2]-1;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    index[0] = size[0]-1; index[1] = size[1]-1; index[2] = 0;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    index[0] = size[0]-1; index[1] = size[1]-1; index[2] = size[2]-1;
    inputImage->TransformIndexToPhysicalPoint(index, point);
    center[0] += point[0]; center[1] += point[1]; center[2] += point[2];

    center[0] /= 8.0; center[1] /= 8.0; center[2] /= 8.0;
```
Consider that it incorrectly measures the size of the image by using the physical points from the bottom-left-front corner of the first voxel and the bottom-left-front corner of the last voxel, thereby failing to include one layer of the image. That's why it reports the center of an image with origin = <-25, -25, -25> as <-0.5, -0.5, -0.5> (e.g., for x: -25 for the four "left" points, and 24 for the four "right" points, added and divided by 8 equals -0.5). 
This value is computed correctly in the new framework.

The next question is why the distribution of points is not as good in the new branch. We've looked at the meshes and while they have values for each point, those value may also be off by -0.5. I'm not sure if that's the reason for the different result, or if some other deprecated executable is still incorrectly computing the center. Please give us a hint as to how the images that are all off by <-0.5,-0.5,-0.5> might be affecting things (@oleks?).

**Comment by akenmorris** [comment]
@cchriste , @archanasri , have you looked at the distance transforms from master and executable side by side in a NRRD volume viewer such as Seg3D2 or ITK-SNAP?  It may help to (inside those tools) threshold and look at the isosurfaces to compare.  What are the differences between the resulting groom files?

**Comment by akenmorris** [comment]
Another option would be to look at them in ShapeWorksStudio.

master:

ellipsoids_master

executable:

ellipsoids_executable

These seem quite a bit different to me.  If you download both images and flip between them it's easier to see the difference.  I don't think this is related to origin/centering.

**Comment by cchriste** [comment]
Hi Alan, 
We have looked very carefully and these images are identical up to the padding stage, after which they are converted to meshes and run through the still-mysterious TPGAC filter to create a rigid transformation. Are the images you’re showing meshes (that’s what they appear to be) or volumes? It would be nice to know when the _precomputed_ meshes are used in order to understand if they might be another culprit due to being created in a different physical space (note: the original physical space of the images is the same). As has been clearly identified, there are incorrect computations of image bounds in at least one of the independent executables. The final results are noticeably different, but the seed of these differences is what we need to identify.
Thanks

**Comment by akenmorris** [comment]
Studio is using marching cubes (via VTK) to display the 3d image volumes as a mesh here at iso value of 0.

Where in the ellipsoid example are we converting to meshes?  I thought TPGAC was an ITK image to image filter.

**Comment by sheryjoe** [comment]
TPGAC only smoothes distance transforms. No meshes are generated in the pipeline. Only the rigid alignment entails isosurfacing to align meshes to compute the transformation parameters, which are then applied to input segmentations (images). It is worth comparing the sequence of commands between master and exec branches and making sure that intermediate outputs are "identical". 

Paraview is also another option to visually compare shapes. you could load nrrds (segmentations or distance tranforms) -- multiple of them, generate isosurface (use contour). this way you can overlay multiple isosurface to inspect the difference. Paraview might not load gzip nrrds, so you might want to convert them to "raw" encoding.

**Comment by cchriste** [comment]
COM is now working (committed to executable_improv branch). The main issue was that the old executable antialiases and binarizes the segmentations before and after the translation, and the new GroomUtils wasn't doing that.

> TPGAC only smoothes distance transforms. No meshes are generated in the pipeline. Only the rigid alignment entails isosurfacing to align meshes to compute the transformation parameters, which are then applied to input segmentations (images).
`icp` uses a rigid registration, and right before that is TPGAC (part of topo-preserving-smooth, the command with different output that I'm currently debugging).

>  It is worth comparing the sequence of commands between master and exec branches and making sure that intermediate outputs are "identical".
This is what we've been doing.

> Paraview is also another option to visually compare shapes. you could load nrrds (segmentations or distance tranforms) -- multiple of them, generate isosurface (use contour). this way you can overlay multiple isosurface to inspect the difference. Paraview might not load gzip nrrds, so you might want to convert them to "raw" encoding.

Thanks!

**Pull request merged**
