### PR TITLE
Studio updates

### PR DESCRIPTION
**Pull request by akenmorris**
Fix some issues regarding grooming settings synchronization with groom page.

To assist in addressing #1755, I've added new multiple domains panel and a checkbox to synchronize the groom settings across domains.

image

To address #1611, I've added a compare button with dropdown menu:

Screen Shot 2022-05-20 at 3 42 06 PM

The user can then independently change the opacity for each mesh

Screen Shot 2022-05-20 at 3 42 01 PM

Additionally, the user can display a surface-to-surface distance map:

Screen Shot 2022-05-20 at 3 43 24 PM

To go the other direction, simply choose the opposite mesh in the combo and the comparisons.

### CODE REVIEW

**Comment by iyerkrithika21** [comment]
@akenmorris: Everything looks good!
Only faced one issue. I tried to reopen ellipsoid_multiple_domain_mesh project, and when I tried to redo grooming, Studio crashed. 
Segmentation fault. Not sure what the exact problem is. 

I can open the project and rerun grooming without problems with other projects like ellipsoids.

**Comment by akenmorris** [comment]
Confirmed, I can reproduce:

```
Thread 21 Crashed:
0   ShapeWorksStudio              	       0x106549892 vtkDiscreteRemeshing<vtkQEMetricForClustering>::DetectNonManifoldOutputVertices() + 1826
1   ShapeWorksStudio              	       0x106540d25 vtkDiscreteRemeshing<vtkQEMetricForClustering>::Remesh() + 1541 (vtkDiscreteRemeshing.h:937)
2   ShapeWorksStudio              	       0x1065300c0 shapeworks::Mesh::remesh(int, double) + 1088 (Mesh.cpp:337)
3   ShapeWorksStudio              	       0x1065054ce shapeworks::Groom::run_mesh_pipeline(shapeworks::Mesh&, shapeworks::GroomParameters) + 254
4   ShapeWorksStudio              	       0x106505b91 shapeworks::Groom::mesh_pipeline(std::__1::shared_ptr<shapeworks::Subject>, unsigned long) + 577
5   ShapeWorksStudio              	       0x106509caf tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, shapeworks::Groom::run()::$_0, tbb::auto_partitioner const>::run_body(tbb::blocked_range<unsigned long>&) + 447
6   ShapeWorksStudio              	       0x106509ab7 tbb::interface9::internal::start_for<tbb::blocked_range<unsigned long>, shapeworks::Groom::run()::$_0, tbb::auto_partitioner const>::execute() + 1239
7   libtbb.dylib                  	       0x10eb7ab99 tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop(tbb::internal::context_guard_helper<false>&, tbb::task*, long) + 393
8   libtbb.dylib                  	       0x10eb7a1b6 tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) + 230
9   libtbb.dylib                  	       0x10eb71835 tbb::internal::arena::process(tbb::internal::generic_scheduler&) + 581
10  libtbb.dylib                  	       0x10eb71045 tbb::internal::market::process(rml::job&) + 53
11  libtbb.dylib                  	       0x10eb6b78d tbb::internal::rml::private_worker::run() + 93
12  libtbb.dylib                  	       0x10eb6b729 tbb::internal::rml::private_worker::thread_routine(void*) + 9
13  libsystem_pthread.dylib       	    0x7ff81f1e04e1 _pthread_start + 125
14  libsystem_pthread.dylib       	    0x7ff81f1dbf6b thread_start + 15
```

**Comment by akenmorris** [comment]
Fixed in 343e324847c165e26297f2dad73fcfdf326d4365

**Comment by akenmorris** [comment]
This branch is merged into the 6.3 release branch which will have a separate PR.

**Review by HeavenlyBerserker — COMMENTED** [review]
Should Constraints be in studio-data? Seems hard to find stuff. Maybe landmarks and constraints should have their own tabs?

**Pull request closed without merging**
