### PR TITLE
Studio updates

### PR DESCRIPTION
**Pull request by akenmorris**
This PR resolves:

#791 - Studio: reset camera on centering change and after grooming with centering
#793 - Studio: Ability to set to two viewers 
#794 - Studio: Allow relative weighting up to 1000
#770 - Studio/Reconstruction - Relax same size constraint on distance transforms

### CODE REVIEW

**Comment by sheryjoe** [comment]
There is an offset/shift between groomed and original data. Any idea why is this happening? 
image
image

**Comment by akenmorris** [comment]
Yeah, this isn't new, the local particles don't get transform with the grooming transform yet.  If you don't run centering, they will be more or less on the surface (other grooming steps will also affect this).  I've added it as an issue #797.

**Comment by akenmorris** [comment]
More specifically, the reason the the particles and original surface are even close is that they are both being centered, but in different ways.  One is using the center of mass of the image and the other is using center of mass of the surface mesh.

**Comment by akenmorris** [comment]
@sheryjoe , this should be fixed now in the latest commit.

**Comment by akenmorris** [comment]
Shall we merge this and create a development build? @sheryjoe

**Review by sheryjoe — APPROVED** [review]

**Pull request merged**
