### PR TITLE
Updated notebooks to use Mesh Python API

### PR DESCRIPTION
**Pull request by archanasri**
This PR should be merged ONLY after Mesh party PR (#949) is merged to master.

### CODE REVIEW

**Review by cchriste — APPROVED** [review]
All these changes look good. I've run all the tests, but I haven't re-run the notebooks. They look like definitely improvements, so if they work and produce the same output, I approve this.

**Comment by sheryjoe** [comment]
@jadie1 @iyerkrithika21 can you run the notebooks?

**Review by jadie1 — APPROVED** [review]
All the notebooks ran as expected for me.

**Comment by iyerkrithika21** [comment]
> 
> 
> All the notebooks ran as expected for me.

It ran for me too, sorry forgot to update here

**Pull request merged**
