### PR TITLE
Scale/Rotate command/function fixes, new resize command/function

### PR DESCRIPTION
**Pull request by cchriste**
biggest items:
- added resize command
- simplified resample command
- fixed scale and rotate commands
- added use cases as options, not merely strings to python example
- updated and added and improved unit tests for image and executable

other:
- un-tabified conda_installs.sh
- improved readability of info command output
- added text to shapeworks --version where release version can be added (and corresponding github issue)

### CODE REVIEW

**Comment by cchriste** [comment]
This is the original image.  
original_image
These images show the fixes to scale and rotate.  
The first column shows the results of scale, with the old version on top and the fixed on the bottom. Note the original image isn't quite centered, so in the bottom the white part is still a little to the left, but it is correctly scaled from the actual center of the original image.  
The second column shows a rotation of -PI/3, old version on top, fixed version on bottom.
scale_rotate_fixes_comparison

**Comment by akenmorris** [comment]
Can you explain a little more about what was broken before with scale and rotate?  Is the the point of reference?

**Comment by cchriste** [comment]
> Can you explain a little more about what was broken before with scale and rotate? Is it the point of reference?

These operations are intended to be performed using the center of the image, and the way that was being set was incorrect. Instead, it now saves the current origin, uses Image::recenter() to change it (what it should have done anyway), and changes it back at the end. The evidence for the origin being set incorrectly is that the rotations and scales appear to be based on the wrong place in the image. This was because it was being set incorrectly.

**Comment by akenmorris** [comment]
Sounds good.  Does this PR change the use cases at all or were they not using these?

**Comment by cchriste** [comment]
> Sounds good. Does this PR change the use cases at all or were they not using these?

The use cases only use isoresample, which was a call to resample that only specifies new physical spacing and allowed the function to automatically compute the new dims, which is what the function will always do now. If explicit resizing is desired, there is now a separate function called Image::resize.

**Comment by cchriste** [comment]
I just made another fix for the info command. The parser wasn't clearing old user-specified arguments, though it was still resetting them to their default values so it was a very invisible issue except for the one command for which we query the number of arguments that were set by the user.

**Comment by cchriste** [comment]
Are we good to go on this?

**Pull request merged**
