### PR TITLE
VectorImage skeleton

### PR DESCRIPTION
**Pull request by cchriste**
Addresses #1005 and #1015 by constructing vector image from a [distance transform] image and providing `evaluate` function to compute best vector at any given point in space.

First pass at #1053.

### CODE REVIEW

**Review by archanasri — APPROVED** [review]

**Comment by akenmorris** [comment]
This will probably be useful for #1005 and #1015, but it's not really approaching #1053.

This isn't really a vector image, this is a wrapper around a scalar image that provides a gradient interpolator to evaluate vectors on the fly.  It can't be used for more general vector images.

A vector image, I would expect to use something like `itk::Image<itk::CovariantVector<float, 3>, 3>`.  Such a `VectorImage` class would be able to directly save and load to NRRD files.

I think what's here in this PR is useful, but I would recommend using a different name.  It's more of a GradientImageWrapper or something like that.

**Comment by cchriste** [comment]
> A vector image, I would expect to use something like `itk::Image<itk::CovariantVector<float, 3>, 3>`. Such a `VectorImage` class would be able to directly save and load to NRRD files.
This is exactly what this type is: `using ImageType = GradientImageFilter::OutputImageType;`

> I think what's here in this PR is useful, but I would recommend using a different name. It's more of a GradientImageWrapper or something like that.
That's why I called it a skeleton. It would be nice not to have a separate class for a vector image since a tremendous amount of functionality is identical. And the `evaluate` function would still be in there, and should actually be there in our current Image class already (it's not, but completely reasonable to add).

**Comment by akenmorris** [comment]
> This is exactly what this type is: using ImageType = GradientImageFilter::OutputImageType;

Yes!  My mistake!

**Comment by akenmorris** [comment]
> That's why I called it a skeleton

Sure, I think it's a fine start.  More stuff will be added later.

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
