### PR TITLE
Usecase upload

### PR DESCRIPTION
**Pull request by 0leks**
Download and upload datasets by name! How exciting!
Check out Documentation/Datasets.md for more details.

Tested on ellipsoid and left_atrium

### CODE REVIEW

**Comment by 0leks** [comment]
Not sure why all the checks failed, I didn't change anything in Shapeworks, just the datasetutils python library and the use case scripts

**Comment by akenmorris** [comment]
@sheryjoe, does Datasets.md look ok?

**Comment by sheryjoe** [comment]
Some comments:
- Add a link to Datasets.md in the UserCase.md and the main ReadME.md.
- For the file structure, I think it is better to standardize the file structure with relevant descriptions (e.g. <data_name>/images, <data_name>/meshes, <data_name>segmentations, <data_name>/constraints, <data_name>/landmarks, <data_name>/meta_data, <data_name>/groom <data_name>/shape_model ... etc).  -- This needs to be added to the Datasets.md and also relfected in the current use cases.
- Give content guidline/examples for README.txt and License.txt
- For APIs, are we adopting the same API naming conventions as GroomUtils, OptimizeUtils and AnalyzeUtils?

**Comment by 0leks** [comment]
> *Add a link to Datasets.md in the UserCase.md and the main ReadME.md.*

Done  

> *For the file structure, I think it is better to standardize the file structure with relevant descriptions (e.g. <data_name>/images, <data_name>/meshes, <data_name>segmentations, <data_name>/constraints, <data_name>/landmarks, <data_name>/meta_data, <data_name>/groom <data_name>/shape_model ... etc).  -- This needs to be added to the Datasets.md and also relfected in the current use cases.*

I'd prefer to do dataset normalization in the next pull request since it will involve contributions from multiple people. 

> *Give content guidline/examples for README.txt and License.txt*

Done, removed README.txt from requirements because don't know what to put in it.

> *For APIs, are we adopting the same API naming conventions as GroomUtils, OptimizeUtils and AnalyzeUtils?*

What naming conventions is this referring to? camel case?
Currently DatasetUtils has 3 functions named as follows: downloadDataset, uploadNewDataset, getDatasetList

**Pull request merged**
