### PR TITLE
Femur no images

### PR DESCRIPTION
**Pull request by jadie1**
Updated femur use case so when --start_with_image_and_segmentation_data is used it grooms images and meshes and when it is not it grooms only meshes.
When not using image, origin and size are inferred from meshes and spacing is isotropic unless the user specifies otherwise.
I updated the documentation to reflect this.

I have already merged this with the usecases branch so it might be better to merge it after pull request #656

### CODE REVIEW

**Comment by cchriste** [comment]
Can this be merged now (after #656)?

**Comment by jadie1** [comment]
@cchriste It's ready to go but I don't know if anyone else has looked at it.

**Comment by jadie1** [comment]
I have fixed the bugs @HeavenlyBerserker found and the femur use case on this branch is running except for in interactive mode. In interactive mode there is a version issue with VTK 9 and Python VTK 8.2.

**Review by HeavenlyBerserker — APPROVED** [review]
Seems to be in order.

Tests now with changes:
  femur
    Without images
       Test subsamples with interactive flag
    With images
       Test subsamples with interactive flag
          Option 2
          Option 1

**Comment by akenmorris** [comment]
Ok, let’s merge the DeepSSM branch first that will fix the VTK stuff.

**Comment by jadie1** [comment]
@sheryjoe @akenmorris I think this is ready to merge

**Pull request merged**
