### PR TITLE
Cut mesh

### PR DESCRIPTION
**Pull request by HeavenlyBerserker**
This PR deals with Joe Mozingo's issue in a more principled and clean way by clipping the mesh before the optimization (#1125). The results look pretty good.

As before, the test dataset used was [joseph_dataset.zip](https://github.com/SCIInstitute/ShapeWorks/files/6137211/joseph_dataset.zip), and can be run by 
`shapeworks optimize --name correspondence_1024.xml`

Screenshot from 2021-03-14 11-38-36
Fig. 1 Shows the results on Joe's dataset

Screenshot from 2021-03-14 11-42-47
Fig. 2 Shows a visualization of the clipping in Paraview. The red wireframe is the original shape and the white surface is the clipped mesh.

### CODE REVIEW

**Review by medakk — CHANGES_REQUESTED** [review]

**Review by akenmorris — CHANGES_REQUESTED** [review]
This looks like it will solve the problem.  Great Job.

But I think we should move the I/O and cutting plane stuff out of VtkMeshWrapper.  Seems like the polydata should just be already cut before being provided to this constructor.  In that respect, I don't think VtkMeshWrapper needs to be touched at all for this change.

Also, we already have an implementation of cutting meshes with clipping planes using vtkClipPolyData in Mesh.cpp (Mesh::clip).  Can we re-use this or is this too different?

**Comment by HeavenlyBerserker** [comment]
@akenmorris Oh, I didn't realize Mesh::clip existed. The mechanism is the same, but I don't want to create a mesh object unnecessarily. I think the easiest way here is to just move the clipping from VtkMeshWrapper::VtkMeshWrapper to where it's constructed at OptimizeParameterFile::read_mesh_inputs and OptimizeParameters::set_up_optimize. Would this be acceptable?

**Comment by akenmorris** [comment]
There's not really any cost to constructing a Mesh class, and we are actually doing it already:

https://github.com/SCIInstitute/ShapeWorks/blob/58ffac86cbea1e7f0b4ede9ff6ded167bd5dfc14/Libs/Optimize/OptimizeParameters.cpp#L281

If you just clip before it calls ::getVTKMesh, then it won't even be creating a new one.

**Comment by akenmorris** [comment]
Looks great. Thanks @HeavenlyBerserker .  I will just commit a style/cleanup commit and then merge it.

**Review by akenmorris — APPROVED** [review]

**Pull request merged**
