### PR TITLE
Fixing Issue #1293

### PR DESCRIPTION
**Pull request by jadie1**
This should fix issue #1293 - path issue in data augmentation on Mac and Windows
To test:
- Run: `pip install ShapeWorks/Python/DataAugmentationUtilsPackage/`
- Run: `pip install ShapeWorks/Python/DeepSSMUtilsPackage/`
- Run the notebook getting-started-with-data-augmentation.ipynb:  `jupyter notebook ShapeWorks/Examples/Python/notebooks/tutorials/getting-started-with-data-augmentation.ipynb` (note you can reduce the number of samples from 50 to like 5 to run it faster)
- Run the DeepSSM use case tiny test: `python RunUseCase.py --use_case deep_ssm --tiny_test`

@iyerkrithika21 Can you test windows?
@archanasri  Can you test Mac?

### CODE REVIEW

**Comment by archanasri** [comment]
Tested it on Mac. The deep_ssm use case works but the notebook throws the same error.

**Comment by jadie1** [comment]
Are the other notebooks working for you? If the use case works I don't think the error is comping from the data augmentation package, I think the notebook isn't finding something the use case is.

**Comment by iyerkrithika21** [comment]
The notebook worked for me on Windows but I had to use setupenv.py to import shapeworks.
```
import os 
import sys
sys.path.append("../../")
import setupenv
setupenv.setup_shapeworks_env(shapeworks_bin_dir="C:\\Program Files\\ShapeWorks\\bin", shapeworks_source_dir="C:\Program Files\ShapeWorks", verbose=False)
import shapeworks
```
All other notebooks will have to be changes as well

**Comment by archanasri** [comment]
> Are the other notebooks working for you? If the use case works I don't think the error is comping from the data augmentation package, I think the notebook isn't finding something the use case is.

Yeah the other notebooks are working for me

**Comment by cchriste** [comment]
> The notebook worked for me on Windows but I had to use setupenv.py to import shapeworks.
> 
> ```
> import os 
> import sys
> sys.path.append("../../")
> import setupenv
> setupenv.setup_shapeworks_env(shapeworks_bin_dir="C:\\Program Files\\ShapeWorks\\bin", shapeworks_source_dir="C:\Program Files\ShapeWorks", verbose=False)
> import shapeworks
> ```
> 
> All other notebooks will have to be changes as well

I'd like to look at this together with someone today before we go and modify our notebooks with things like this. @iyerkrithika21 @jadie1 @archanasri ?

**Comment by cchriste** [comment]
> Tested it on Mac. The deep_ssm use case works but the notebook throws the same error.

What error is the notebook throwing?

**Comment by cchriste** [comment]
> > All other notebooks will have to be changes as well
> 
> Did you create an issue for this? If not, please do that and assign it both of us and we can look into it today.
> We definitely don't want to burden users to import our module, in or out of notebooks.

I just created #1313, which may be what we need. But I don't know if you were working from an installed version or a development version.

**Comment by jadie1** [comment]
@Archana and I tested the change I just pushed on Linux and Mac and it worked. We just changed the data aug utils package to use all pybind instead of calling a command line function and that fixed it without doing anything like using setupenv.

@iyerkrithika21 could you test this on windows? You will need to rerun: `pip install ShapeWorks/Python/DataAugmentationUtilsPackage/`

**Comment by iyerkrithika21** [comment]
Facing the same issue as #1317 while testing the Windows build

**Comment by jadie1** [comment]
@iyerkrithika21 when you test the dev build on this branch is the issue fixed? If so we can merge this PR, #1317 will be a separate PR.

**Comment by cchriste** [comment]
Since everything is working, we can go ahead and merge this.

**Pull request merged**
