### PR TITLE
One mode ellipsoid

### PR DESCRIPTION
**Pull request by jadie1**
This PR changes all ellipsoid examples to use new ellipsoid data generated via the shape cohort generator which only varies along the x radius. Addresses issue #1133

Testing required:

- [ ] ellipsoid use case
- [ ] ellipsoid_fd use case
- [ ] ellipsoid_mesh use case
- [ ] ellipsoid_cut use case
- [ ] getting-started-with-segmentations.ipynb
- [ ] getting-started-with-meshes.ipynb
- [ ] getting-started-with-exploring-segmentations.ipynb 
- [ ] getting-started-with-grooming-segmentations.ipynb
- [ ] getting-started-with-shape-cohort-generation.ipynb 

When the new data on the portal (ellipsoid_1mode and ellipsoid_1mode_aligned) have the expected output from all use cases except ellipsoid_cut (PR #1157)

### CODE REVIEW

**Comment by sheryjoe** [comment]
related to #1082?

**Comment by jadie1** [comment]
> related to #1082?

Yes fixes #1082

**Comment by akenmorris** [comment]
Trying to figure out why a 100mb zip file was committed to this branch instead of git-lfs.  You don't have git-lfs installed?

**Comment by akenmorris** [comment]
See #1162 for PR without large file.

**Pull request closed without merging**
