### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by AtefehKashani**
More details and snapshots are added to the use case documentations.

### CODE REVIEW

**Comment by akenmorris** [comment]
@sheryjoe , is this ok to merge?

**Comment by AtefehKashani** [comment]
I have added the gif files for left atrium, it is good to go on my side.

**Comment by sheryjoe** [comment]
Are the optimization parameters listed in the UseCase.md file the ones used to build the demonstrated shape models?

Otherwise, looks good to me.

**Comment by AtefehKashani** [comment]
The optimization parameters for the left atrium is consistent with the
illustrated model.

**Comment by jadie1** [comment]
The femur optimization parameters are also consistent.

**Comment by sheryjoe** [comment]
This is ready for merge then.

**Pull request merged**
