### PR TITLE
Optimize command

### PR DESCRIPTION
**Pull request by akenmorris**
This PR adds the "optimize" command (#567).

Usage:

shapeworks optimize --name=file.xml

ShapeWorkRun has been removed
Python use cases have been modified to use 'shapeworks optimize'

### CODE REVIEW

**Review by medakk — APPROVED** [review]
Looks good. I added a commit to update some docs

**Comment by sheryjoe** [comment]
Can we merge this and close the issue?

**Comment by sheryjoe** [comment]
Is this ready to be merged? @akenmorris

**Comment by akenmorris** [comment]
Yes, was just waiting for the checks to complete.

**Pull request merged**
