### PR TITLE
Usecases

### PR DESCRIPTION
**Pull request by AtefehKashani**
addressed issue #549 
**left atrium, femur** :  addressed for running with less number of particles and less number of  iterations.
**left atrium**: added running with prep data using the downloaded distance transforms.

### CODE REVIEW

**Comment by cchriste** [comment]
This looks good. Does it still test everything? For example, when using single scale? How long do the tiny tests now take to run?

**Comment by jadie1** [comment]
This looks good to me, I added the option to skip grooming in the Femur use case with --start_with_prepped_data and run the tiny test

**Comment by AtefehKashani** [comment]
@cchriste if you run with prep_data it will be done in less than 2 minutes. If you want to test the grooming it takes longer(because of the rigid alignment step), but still will not take longer than 5 minutes.

**Comment by cchriste** [comment]
Please delete this branch if you're done with it.

**Comment by sheryjoe** [comment]
@cchriste can we merge master to exec-auto-doc (branched from exectuable_improv? I am trying to run tiny test but taking significant time.

**Comment by sheryjoe** [comment]
exec-auto-doc  is now up to date with master.

**Pull request merged**
