### PR TITLE
More testing

### PR DESCRIPTION
**Pull request by akenmorris**
Reorganize Testing structure into Testing folder, switch to git-lfs for nrrd files, add ImageTests with test for resample.

### CODE REVIEW

**Comment by cchriste** [comment]
I'm trying to test and git-lfs us used to store the testing data. Unfortunately I can't remember how to use it and I can't find any documentation to explain it. Is there something I'm missing? Due to this, the tests themselves fail.

**Comment by cchriste** [comment]
```git lfs fetch

**Comment by akenmorris** [comment]
We can switch to operator== if you want.  Will it be confusing if someone wants to use it with a (smart) pointer to an Image?

**Comment by akenmorris** [comment]
I'm not a super git lfs expert by any means.  I believe you only have to do those steps because you're adding it to an existing clone.  If the git-lfs stuff was merged and you had it installed, I believe it would be seamless.

**Pull request merged**
