### PR TITLE
Reorganize and consolidate libraries

### PR DESCRIPTION
**Pull request by cchriste**
Consolidated libraries as we discussed at our meeting last Thursday, now we have:
**Alignment/
Analyze/
Image/
Mesh/
Optimize/
Utils/**

Have built from scratch to ensure everything works, tested our guis and latest python demonstrations. Let's please get this merged ASAP since any work may be on files that have moved and this could be confusing or more challenging to merge as time goes on. It's a solid, stable branch with appropriate directory structure and clarity. Thanks!

### CODE REVIEW

**Comment by cchriste** [comment]
Thanks, Shireen. I did `make clean` but apparently it still keeps things
around like old libs. For example, -lFoo will look for the library named
Foo and fail if it doesn't exist. I thought I'd ensured our old libs were
no longer being requested but `make clean` wasn't sufficient. So now I've
completely deleted the build/shapeworks directory to ensure nothing is
there that's not supposed to be. Ready to merge!

**Comment by sheryjoe** [comment]
To be addressed before the merge:
- TriMesh (fim_v4) should be in Libs till we extract and isolate our additions to this library.
- Examples should have Scripts (containing .sh scripts currently in Examples) and Python (containing use cases) folders.
- Another name for Utils.* to avoid conflict with other libs utils
- Inconsistencies in Libs/XX/"sublibs" - example, Libs/Mesh/PreviewMeshQC verus Libs/Reconstruction.* 

The below could be addressed after this merge in different branch(s):
- File extensions consistency (txx vs cxx vs cpp)
- Get rid of "itk" prefix in file names and classes (esp the particle system)
- Command line tools in Libs to be converted to classes with calling APIs for cmd/studio/cloud tools.
- consolidate shapeworks executable
-

**Comment by cchriste** [comment]
> To be addressed before the merge:
> 
> * TriMesh (fim_v4) should be in Libs till we extract and isolate our additions to this library.
Nothing should be in ExternalLibs, so everything there is meant to be pulled in by cmake's ExternalProject_Add. I'm aware of our Trimesh modifications and putting this lib in ExternalLibs is the first step towards resolving issue #89, mentioned in several other places, including the commit that moved trimesh.

> * Examples should have Scripts (containing .sh scripts currently in Examples) and Python (containing use cases) folders.
Done.

> * Another name for Utils.* to avoid conflict with other libs utils
Can this please be done after the merge? I need to commit time to another project and the Utils is as it has been all along. Just like the itk-prefixed files mentioned below, not really a reorganization task.

> * Inconsistencies in Libs/XX/"sublibs" - example, Libs/Mesh/PreviewMeshQC verus Libs/Reconstruction.*
I would argue all files for a given library should be in its top-level directory, but some of these consolidations involved lots of files (another example is the [itk]ParticleSystem files. They could be moved up, but perhaps also reduced to fewer files. As it stands, this is an incremental process and this first step seems reasonable. I would strongly argue _against_ creating a zillion subdirectories within each lib, but a few might be useful. Again, this is a good start and can be incrementally improved. 

> 
> The below could be addressed after this merge in different branch(s):
> 
> * File extensions consistency (txx vs cxx vs cpp)
Totally agree! Same for cxx and cpp, which should all be cpp.

> * Get rid of "itk" prefix in file names and classes (esp the particle system)
I started this and it is a big task so I feel it should be addressed incrementally after this merge is complete.

> * Command line tools in Libs to be converted to classes with calling APIs for cmd/studio/cloud tools.
> * consolidate shapeworks executable
Yup!

**Comment by cchriste** [comment]
> * UseCaseDocumentation should be renamed to Python and only include shapeworks python library. Use cases should be moved to Examples/Python and use the lib in ShapeWorks/Python. Pdfs in UseCaseDocumentation should be moved to Documentation.

I wasn't sure their purpose since those pdfs were added recently. I agree they should go in Documentation.

I agree we should have a Python folder for the ShapeWorks Python API, which doesn't yet exist. So all our examples are in Examples as they should be. If a different organization is desired, perhaps it would best be done by the people closer to these scripts _after the merge_.

**Comment by akenmorris** [comment]
Regarding CMAKE_BUILD_TYPE. I found inconsistent values for this across the different CMake files.

**Comment by cchriste** [comment]
I've seen Alan's comments on Slack (ellipsoid, studio and view2 are all working). Can we go ahead and merge now?

**Comment by cchriste** [comment]
Everything seems good to go so I’m going to merge now.

**Pull request merged**
