### PR TITLE
Stats-pvalues for the group difference

### PR DESCRIPTION
**Pull request by iyerkrithika21**
@akenmorris/ @jadie1  can you upload the dataset to the portal [femur_stats.zip](https://github.com/SCIInstitute/ShapeWorks/files/6864554/femur_stats.zip)
This dataset has the shape model for femur with the group ids.
This PR includes the stats function to calculate the p-values for the group difference and includes a use case. 

To test the PR run - `python RunUseCase.py femur_pvalues`

### CODE REVIEW

**Comment by akenmorris** [comment]
Where do we need to upload it?  As use-case-data-v2/femur_pvalues-v0  ?

**Comment by akenmorris** [comment]
```
    from hotelling.stats import hotelling_t2
ModuleNotFoundError: No module named 'hotelling'
```

Am I missing a package?

**Comment by iyerkrithika21** [comment]
> 
> 
> ```
>     from hotelling.stats import hotelling_t2
> ModuleNotFoundError: No module named 'hotelling'
> ```
> 
> Am I missing a package?

Oh sorry! 
I will update the install script with this package.

**Comment by iyerkrithika21** [comment]
> 
> 
> Where do we need to upload it? As `use-case-data-v2/femur_pvalues-v0` ?
Yes. 

I will change the dataset name in the code to -femur_pvalues-v0.

**Review by akenmorris — APPROVED** [review]
Looks good to me.  I've added an automated test and uploaded the data.

I'll need to modify this when we integrate into studio, but we can cross that bridge when we come to it.

**Pull request merged**
